project:
  type: website
  output-dir: _docs
  execute-dir: project
  
freeze: auto

website:
  title: "MEAPS"
  search: true
  open-graph: true
  twitter-card: true
  site-url: "https://preview.meaps.fr/"
  repo-url: "https://github.com/xtimbeau/meaps/"
  google-analytics: "G-KF6Z4B486X"
  reader-mode: true
  bread-crumbs: true
  comments:
    utterances:
      repo: "xtimbeau/meaps"
      label: "comment"
      theme: "github-light"
  page-footer:
      border: true
      center: "**CC BY 4.0**"
  navbar: 
    title: false
    search: true
    bakground: "#FEFEFE"
    logo: www/ofce_m.png
    logo-alt: "OFCE"
    logo-href: "https://www.ofce.fr/"
    left:
      - text: "{{< iconify game-icons mesh-network >}} MEAPS"
        file: index.qmd
      - text: "{{< iconify fluent clipboard-math-formula-16-regular >}} Théorie"
        menu:
          - text: "Version française"
            file: theorie.qmd
          - text: "English version"
            file: theorie.en.qmd
      - text: "Estimations"
        icon: database-check
        file: larochelle.qmd
      - text: "{{< iconify gis statistic-map >}} Projection"
        file: trajets.qmd
      - text: "{{< iconify ri presentation-line >}} Présentations"
        file: presentations.qmd
      - text: "Références"
        icon: book
        file: references.qmd
    right:
      - text: "A propos"
        icon: person-circle
        file: about.qmd
      - text: " "
        icon: github
        url: "https://github.com/xtimbeau/meaps"
      
logo: www/ofce.png

format:
  wp-html: default

editor: visual

babelquarto:
  languagecodes:
  - name: en
    text: "English version"
  - name: fr
    text: "Version en français"
  mainlanguage: 'fr'
  languages: ['en']
title-en: title in en
description-en: description in en
author-en: author in en
