project:
  type: book
  output-dir: docs

book:
  title: "MEAPS"
  subtitle: "Distribution statistique des trajets entre le domicile et des opportunités"
  page-footer: "version provisoire, merci de ne pas citer ou diffuser"
  author:
    - name : Maxime Parodi
      email: "maxime.parodi@sciencespo.fr"
      affiliation: OFCE, Sciences po Paris
    - name: Xavier Timbeau 
      email: "xavier.timbeau@sciencespo.fr"
      affiliation: OFCE, Ecole Urbaine, Sciences po Paris
  date: 02/01/2023
  output-file: "meaps"
  cover-image: www/cover.png
  search: true
  site-url: https://xtimbeau.github.io/meaps/
  repo-url: https://github.com/xtimbeau/meaps/
  open-graph: true
  twitter-card:
    creator: "XTimbeau"
  repo-actions: [edit]
  reader-mode: true
  downloads: [pdf, epub]
  sharing: [twitter, linkedin, facebook]
  chapters:
    - index.qmd
    - intro.qmd
    - theorie.qmd
    - simsynth.qmd
    - larochelle.qmd
    - references.qmd

bibliography: references.bib

author-title: Auteurs

citation:
  type: article
  container-title: "Document de travail de l'OFCE"
  url: https://xtimbeau.github.io/meaps

keywords: [ modèle gravitaire, modèle radiatif, mobilités ]
lang: fr
crossref:
  fig-prefix: figure   
  tbl-prefix: tableau
  eq-prefix: équation
  sec-prefix: section
  fig-title: figure
  tbl-title: tableau
  lof-title: Figures
  lot-title: Tableaux
comments:
  hypothesis: true
logo: www/ofce.png
format: 
  html:
    theme:
      light:
        - litera
        - www/custom.scss
      dark:
        - darkly
        - www/custom.scss
    date-modified: today
    toc: true
    toc-title: Dans cette partie
    toc-location: left 
    number-sections: true
    number-depth: 3 
    html-math-method: katex
    fig-dpi: 600
    fig-format: png
    fig-width: 5
    cap-location: margin
    reference-location: margin
    code-tools: true
  pdf:
    toc: true
    toc-depth: 1
    number-sections: true
    number-depth: 3 
    documentclass: scrreprt
    classoption: 
    - DIV=9
    papersize: a4
    fontsize: 10pt
    fig-cap-location: bottom
    include-in-header: 'preamble.tex'
    extra_dependencies: ["float"]
    fig-dpi: 600
    fig-format: png

editor: visual