project:
  type: book
  output-dir: docs
  execute-dir: project

book:
  title: "MEAPS"
  subtitle: "Distribution statistique des trajets entre le domicile et le travail"
  page-footer: 
    border: true
    center: "**CC BY 4.0**"
  author:
    - name : "Maxime Parodi"
      email: "maxime.parodi@sciencespo.fr"
      affiliation: OFCE, Sciences po Paris
      affiliation-url: "http://www.ofce.fr"
    - name: "Xavier Timbeau" 
      email: "xavier.timbeau@sciencespo.fr"
      affiliation: OFCE, Ecole Urbaine, Sciences po Paris
      affiliation-url: "http://www.ofce.fr"
      orcid: "0000-0002-6198-5953"
  date: 02/01/2023
  output-file: "meaps"
  cover-image: www/cover.png
  search: true
  open-graph: true
  twitter-card: true
  site-url: "https://xtimbeau.github.io/meaps/"
  repo-url: "https://github.com/xtimbeau/meaps/"
  google-analytics: "G-KF6Z4B486X"
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, linkedin, facebook]
  sidebar:
    footer: "<em>version provisoire, merci de ne pas diffuser ni de ne pas citer</em>"
  chapters:
    - index.qmd
    - intro.qmd
    - theorie.qmd
    - simsynth.qmd
    - larochelle.qmd
    - scenarios.qmd
    - references.qmd

bibliography: references.bib

author-title: Auteurs

citation:
  type: article
  container-title: "Document de travail de l'OFCE"
  url: "https://xtimbeau.github.io/meaps"

keywords: [ modèle gravitaire, modèle radiatif, mobilités ]
lang: fr
crossref:
  fig-prefix: figure   
  tbl-prefix: tableau
  eq-prefix: équation
  sec-prefix: section
  fig-title: figure
  tbl-title: tableau
  lof-title: Figures
  lot-title: Tableaux
comments:
  hypothesis: true
logo: www/ofce.png
format: 
  html:
    theme:
      light:
        - cosmo
        - www/meaps.scss
      dark:
        - darkly
        - www/custom.scss
    date-modified: today
    toc: true
    toc-location: left 
    toc-title: Sur cette page
    number-sections: true
    number-depth: 3 
    html-math-method: katex
    fig-dpi: 600
    fig-format: png
    fig-width: 5
    cap-location: margin
    reference-location: margin
    code-tools: true
  pdf:
    toc: true
    toc-depth: 1
    number-sections: true
    number-depth: 3 
    documentclass: scrreprt
    classoption: 
    - DIV=9
    papersize: a4
    fontsize: 10pt
    fig-cap-location: bottom
    include-in-header: 'www/preamble.tex'
    extra_dependencies: ["float"]
    fig-dpi: 600
    fig-format: png

editor: visual