# Tobler n'implique pas la gravité

Dans l'analyse des phénomènes spatiaux, la distance joue un rôle important. Cette évidence est ce qu'on appelle parfois le principe de Tobler :

> Tout est relié mais les choses proches sont plus reliées que les choses éloignées.

Si nous prenons l'exemple de l'appariement géographique des emplois et des résidents, la proximité de l'emploi est un facteur incontournable, même si d'autres facteurs interviennent dans le choix d'un emploi : le salaire, les compétences, etc. Le rôle de la distance lors du choix d'un emploi est évalué généralement à l'aide d'un modèle gravitaire. Peu d'alternatives ont été étudiées dans la littérature et le modèle gravitaire s'est imposé comme un standard, un outil que l'on peut oublier pour se consacrer à la prise en compte des autres facteurs.

Pourtant, en nous intéressant à la mobilité de la vie quotidienne à une échelle géographique fine -- le carreau 200m -- nous nous sommes heurtés aux limites du modèle gravitaire, en particulier lorsqu'il a fallu se prononcer sur des scénarios de relocalisation de l'emploi. Ces limites tiennent à ce que le modèle gravitaire réduit le principe de Tobler à une mesure *homogène* de la distance. Il est possible d'améliorer nettement la compréhension des territoires en passant de la distance aux temps de transport selon les différents modes possibles. Plus finement encore, il est possible de passer à une notion de *coût généralisé* d'un déplacement, qui prend en compte différents aspects de ce trajet (son coût monétaire, son confort, sa fiabilité, etc.). Toutefois, ces améliorations de la "métrique" - certes indiscutables - ne font que changer l'*input* du modèle gravitaire, sans l'interroger. Or ce modèle souffre d'un défaut plus fondamental : il évacue ce qui fait la spécificité du spatial en voulant réduire celui-ci à une variable unidimensionnelle ; il évacue le fait que l'espace est habité et que chaque lieu est défini aussi par son voisinage.

Ainsi, le modèle gravitaire traite de la même façon les milieux urbains denses et les zones rurales. Il faudrait croire, par exemple, qu'un trajet d'une demi-heure en voiture est aussi pénible pour un gilet jaune que pour un Parisien. Or ce n'est évidemment pas le cas : celui qui réside en milieu rural fait de nécessité vertu et finit même par apprécier ces longs trajets quotidiens, tandis que celui qui reside dans des zones fortement urbanisées envisage des alternatives puisqu'il dispose d'un plus large éventail de possibles pour satisfaire ses demandes. Le défaut du modèle gravitaire n'est pas ici une simlple histoire de relation subjective au temps de trajets. Plus fondamentalement, le défaut tient à ce que ce modèle ne voit pas l'espace ; il ne voit pas ce que le territoire offre ; il ne voit pas qu'en zone urbaine l'offre (d'emplois, de services, ...) est plus ramassée et que cela change la manière de traiter les distances relatives et les coûts relatifs. La conséquence de cet aveuglement est que l'offre sur le territoire est traité *comme si* elle était homogène. Supposons, par exemple, que les pouvoirs publics souhaitent créer une zone industrielle offrant de nouveaux emplois. Le modèle gravitaire conduira à penser que les résidents en zone rural, parce qu'ils sont très parsemés, sont le plus souvent trop éloignés de la nouvelle zone d'emplois pour être intéressés : dans l'arbitrage entre utilité de l'emploi et coût du trajet, ce dernier devient rapidement si élevé qu'il semble préférable de renoncer à l'emploi. Or, l'arbitrage réel est loin d'être aussi simpliste car, bien entendu, un individu qui ne trouve pas d'emplois à proximité se résignera à faire plus de kilomètres pour travailler que quelqu'un qui, au contraire, vit près d'un centre économique dynamique. La distance ne pèse pas du même poids selon la quantité d'offre dans le voisinage.

Face à ces anomalies liées au modèle gravitaire, nous proposons de nous appuyer sur une autre analogie : celle de la traversée par un flux de particules d'un matériau composé de sites d'absorption hétérogènes. Si l'on cherche un emploi dans une zone riche en emplois, la chance d'être satisfait à proximité de son point de départ sera importante, comme l'est la chance d'une particule d'être rapidement absorbée lorsqu'elle est entourée de sites absorbants. A l'inverse, si les emplois sont peu denses là où on réside, la distance à parcourir sera probablement plus grande, comme une particule traversant une zone de vide. En fait, la chance d'être absorbée ne dépend pas directement de la distance au site réceptacle ; elle dépend du nombre de sites qui sont traversées avant celui-ci. Ou, disons encore, elle dépend du rang de ce site dans le classement des sites du plus proche au plus éloigné. Cette analogie se trouve déjà chez @stouffer1940 et @simini2012. Toutefois, les modèles qu'ils ont développés peuvent encore être améliorés, notamment en modélisant le fait que les sites d'absorption peuvent avoir une capacité limitée. Nous proposons donc un modèle qui tient compte de l'absorption et de la saturation. Il est de nature stochastique et, par un raisonnement de physique statistique, nous pouvons conjecturer une stationnarité des principales prédictions. Nous l'avons appelé Modèle Ergodique à Absorption et Saturation, qui s'abrège en *MEAPS*.

Ce modèle respecte tout autant le principe que ce qui est proche joue -- toutes choses égales par ailleurs -- un rôle plus important que ce qui est loin. Mais au lieu de la distance, on utilise le rang dans le classement des distances. La différence peut sembler mineure, mais elle répond à la question de l'hétérogénéité spatiale et de la densité des milieux traversés. Dans le modèle gravitaire, il arrive toujours un moment où, pour prendre encore un autre exemple, l'école est trop éloigné et où ça ne "vaut" plus le coût. Dans la perspective initiée par Stouffer, et reprise ici, l'école la plus proche, celle de rang 1, aussi éloignée soit-elle, demeure utile précisément parce qu'elle est la plus proche. La remarquable série de documentaires intitulée "*Les chemins de l'école*" souligne parfaitement que l'école la plus proche vaut toujours le coup, même si les écoliers doivent marcher plusieurs heures pour y aller.

L'analogie employée permet de considérer le processus d'appariement comme résultant d'une procédure de recherche qui examinerait les opportunités dans l'ordre de leur proximité. Une telle procédure permet de spécifier des comportements qui servent de référence et d'hypothèse nulle pour se confronter aux données. Des amendements à la marge de cette procédure de recherche pourront produire un meilleur ajustement et s'interpréter directement. Pour l'heure, nous oublions ici tous les autres déterminants de l'appariement, comme le salaire, les compétences demandées ou offertes ou encore le secteur d'activités. Nous ajustons un modèle réduit à l'argument de la distance sur des données riches, issues du recensement français et mesurant les flux entre communes de résidence et communes d'emplois. Sous l'hypothèse que tous les emplois ne diffèrent que par leur localisation, nous parvenons à un ajustement de données bien meilleur que le modèle gravitaire. Des données plus riches -- à supposer qu'elles existent -- pourraient améliorer encore l'ajustement en introduisant les différences de salaires ou de compétences. Cependant, une prise en compte plus rigoureuse de la géographie nous semble une première étape essentielle, puisqu'elle modifie d'un ordre de grandeur au moins la qualité de l'ajustement.

L'approche est donc structurelle : c'est un modèle même frustre qui définit la façon dont oin peut interpréter les données. Les données sans le modèles ne veulent pas dire grand chose, le modèle sans les données n'est que spéculation, et, suivant l'injonction de Kant, nous associons l'un avec les autres pour décrire la réalité.

Le document décrit dans un premier chapitre ([-@sec-theorie]) la construction du modèle théorique. Nous y développons la critique du modèle gravitaire et filons l'analogie du modèle radiatif. Le modèle complet n'est pas solvable dans une forme fermée. Nous décrivons donc un algorithme qui permet de le calculer. Dans un second chapitre ([-@sec-synt]) nous analysons les principales propriétés du modèle théorique sur des simulations synthétiques, c'est-à-dire générés explicitement. Ceci permet en particulier de donner de la vraisemblance, à défaut d'une démonstration, à la propriété d'ergodicité du modèle, qui conditionne la possibilité de le simuler. Dans le chapitre [-@sec-rochelle], nous procédons à l'ajustement empirique de *MEAPS* sur des données pour l'agglomération de Rochelle, -- les données de flux communes à communes issues du recensement, mais également une information précise sur la localisation des résidents, des emplois et la structure des réseaux de transport. Nous décrivons en détail la construction de ces données. Nous procédons ensuite à une série d'estimations non paramétriques en modifiant le modèle théorique pour intégrer ce qui s'apparente à des effets fixes. L'estimation paramétrique de plusieurs modèles spécifiés à partir de *MEAPS* et du modèle gravitaire permet de conclure à la supériorité de la famille *MEAPS* quant à la prise en compte de la géographie. Dans le chapitre [-@sec-scenarios] nous utilisons *MEAPS*, ajusté sur les données, pour explorer la réponse à des questions du type "que se passe-t-il si..." pour lesquelles le modèle gravitaire produisait des résultats contestables et qui nous a conduit à le reconsidérer.
