---
title: "Accessibilité à l'emploi et marché du travail"
author: Xavier Timbeau (xavier.timbeau@sciencespo.fr)
format:
  note-pdf: default
  docx: default
date: 2024-01-20
editor: visual
toc: FALSE
bibliography: references_meaps.bib
---

Depuis 2021, nous menons à l'OFCE des travaux de recherche en géographie économique et urbaine, en explorant les différentes dimensions de la façon dont sont répartis et connectés les habitants et leurs centres d'intérêt. Ces problématiques sont liées à celles qui s'intéressent aux liens entre population et emploi, mais aussi à celles qui s'attachent à comprendre les mobilités quotidiennes, en particulier les mobilités domicile travail. Dans nos travaux, nous avons développé des méthodes originales qui permettent d'intégrer finement la question de l'emploi et celle des mobilités.

Ainsi un travail initié à la Rochelle et développé actuellement sur l’agglomération d'Aix-Marseille-Provence a été centré sur la question des mobilités et du bilan carbone qui y est associé. En s'inspirant des modèles de mobilités (modèles à 4 étapes ou modèles L(and)U(se)T(ransport)Interaction, nous avons construit un modèle à haute résolution géographique, facilement manipulable (et donc un peu moins ambitieux que les modèles complets LUTI ou à 4 étapes) qui peut être estimé à partir de données géographiques sur les localisations (les résidents, les emplois, les aménités) mais aussi les flux (comme les données du recensement, ou encore les données de téléphone mobile avec Fluxvision d'Orange), tout en produisant des analyses à une résolution au carreau 200m. Le choix de cette résolution n'est pas fortuit : cela permet aux acteurs une appropriation forte parce qu'on peut intégrer des éléments fins de la géographie comme, à l'extrême, analyser ce que le changement d'emplacement d'un arrêt de bus peut produire sur l'accessibilité à l'emploi et induire comme modification des émissions de CO~2~ imputées à la mobilité quotidienne. Au delà de l'anecdote, l'échelle de représentation est essentielle pour engager les acteurs.

A ce stade nous avons publiés plusieurs éléments, décrivant le modèle théorique, les méthodes empiriques ou encore une application à la Rochelle qui est l'occasion d'une discussion sur la notion de densité (<https://preview.meaps.fr>). Nous insistons en particulier sur l'idée que lorsqu'il s'agit de réduire les mobilités carbonées l'important est de faire en sorte que les résidents puissent se rendre à leurs emplois en effectuant des distances plus courtes et en utilisant des moyens de transport moins carbonés. Ce qui peut paraître évident au premier abord dénote avec les principales conclusions de la littérature en géographie économique qui se limite à relier émissions (ou kilomètres parcourus en voiture) et densité résidentielle. Or nous montrons que c'est une vue partielle qui oublie que l'important est la position des résidents par rapport à leurs emplois, plus pertinente que la seule densité. Dans le cas de la Rochelle, on peut donc faire apparaître des zones peu denses, mais bine desservies, proches des emplois que l'on gagnerait à densifier. A l'opposé, des zones denses peuvent être assez loin de l'emploi, particulièrement dans des territoires façonnés par la voiture ou par l'évolution des prix de l'immobilier qui ont poussé des résidents moins fortunés loin de l’accessibilité à l'emploi.

Pour la métropole d'Aix-Marseille-Provence, nous avons obtenu un résultat intéressant : si l'accessibilité à l'emploi n'est pas l'apanage des plus riches, du fait d'une structure de ségrégation spatiale assez atypique à Marseille – plus proche des modèles américains aux centres-villes délabrés et aux périphéries proches de la nature et aisées, lorsque le marché du travail s'améliore, ce sont les plus proches de l'emploi qui en profite le plus, en particulier lorsqu'ils sont moins riches et dépendent des transport en commun pour leurs déplacements.

Dans la suite de ces travaux, nous voulons prolonger cette voie de recherche sur le lien entre fonctionnement du marché du travail et formes urbaines. Notre hypothèse est que les entreprises ont besoin pour se développer d'avoir accès à des salariés potentiels, mais que ceux-ci sont peu mobiles. S'ils sont loin, par leurs qualifications, leurs exigences salariales mais aussi leur situation géographique, les entreprises ne pourront pas recruter et les individus restent sans emploi. L'idée est donc d'explorer sous l'angle des difficultés de recrutement la dissociation spatiale entre logements et emplois.

Plus spécifiquement, nous prévoyons utiliser les données de "Besoin de Main d'Œuvre" (BMO) d'un côté, de l'autre notre méthode de construction de l'accessibilité à l'emploi à une échelle fine. En accédant aux données sécurisées par le CASD, nous pouvons utiliser la localisation à la commune des 2 millions d'entreprises déclarantes et leur associer les difficultés de recrutement qu'elles déclarent. Nous sommes en discussion avec l'INSEE pour pouvoir accéder à une localisation à l'adresse qui augmenterait considérablement l'information de localisation.

Combinant réseau de transport, localisation des logements en fonction de leurs prix, nous pouvons évaluer, pour chaque entreprise déclarante à combien d'emplois elle peut accéder. En intégrant géographiquement les entreprises, nous pouvons également déterminer le degré de concurrence dans l'accès aux salariés.

Compte tenu de la richesse des données et de leur profondeur à la fois spatiale et temporelle, nous pouvons éventuellement construire des échantillons permettant une meilleure identification des paramètres d'intérêts (comme un investissement important dans un nouveau site impliquant un effort de recrutement massif).

Un résultat de cette recherche sera de pouvoir identifier une composante "spatiale" aux difficultés de recrutement, qui nous l'espérons sera une part importante de ces difficultés de recrutement. En termes de politique publique, un tel résultat est important pour allouer une part de l'effort vers la résolution de ce mésappariement spatial par le développement ou le renforcement de réseaux de transport, la construction de nouveaux logements ou encore l'attribution de logements à loyers modérés là où les offres d'emplois sont nombreuses et peu satisfaites. Nous pensons que ces éléments sont négligés dans le diagnostic et qu'ils méritent une attention plus sérieuse.

Le travail de recherche envisagé est plutôt lourd. Il demande la mise en œuvre de méthodes avancées sur des données complexes à utiliser. Nous estimons le coût de ce projet à 18 mois d'un temps plein pour un post doctorant, ce qui, en ajoutant les frais liés aux données représente un budget de recherche de l'ordre 100k€ – sans valoriser le temps de travail des permanents actuellement travaillant sur ce projet. Nous déposerons en septembre une demande de financement auprès du PUCA (Plan Urbanisme Construction Architecture) dans la thématique évaluation du besoin en logements sous l'angle de l'emploi.

Dans le cadre de ce projet, un partenariat avec la CFE-CGC a un intérêt majeur pour notre équipe de recherche. Outre un intérêt commun sur cette recherche, nous pensons pouvoir nous nourrir des compétences et de l'expérience de terrain des syndicats, acteurs en particulier d'Action logement, pour affiner nos hypothèses comme nos recommandations. Vis-à-vis du PUCA, cela nous permettrait de faire état d'un intérêt pour les résultats de cette recherche et donc de pouvoir alimenter le débat public sur cette question essentielle pour celui qui s'intéresse au dynamisme économique de notre pays.
