<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr" xml:lang="fr"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="keywords" content="modèle gravitaire, modèle radiatif, mobilités">

<title>MEAPS : Distribution statistique des trajets entre le domicile et le travail - 3&nbsp; Application à la Rochelle</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./references.html" rel="next">
<link href="./simsynth.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Pas de résultats",
    "search-matching-documents-text": "documents trouvés",
    "search-copy-link-title": "Copier le lien vers la recherche",
    "search-hide-matches-text": "Cacher les correspondances additionnelles",
    "search-more-match-text": "correspondance de plus dans ce document",
    "search-more-matches-text": "correspondances de plus dans ce document",
    "search-clear-button-title": "Effacer",
    "search-detached-cancel-button-title": "Annuler",
    "search-submit-button-title": "Envoyer"
  }
}</script>
<script async="" src="https://hypothes.is/embed.js"></script>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css">

</head>

<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Application à la Rochelle</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">MEAPS : Distribution statistique des trajets entre le domicile et le travail</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Résumé</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">Introduction générale</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./theorie.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Aspects théoriques de MEAPS</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./simsynth.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">MEAPS : Simulations synthétiques</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./larochelle.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Application à la Rochelle</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">Références bibliographiques</a>
  </div>
</li>
    </ul>
    </div>
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table des matières</h2>
   
  <ul>
  <li><a href="#sec-rochelle" id="toc-sec-rochelle" class="nav-link active" data-scroll-target="#sec-rochelle"><span class="toc-section-number">3.1</span>  Une application à l’agglomération de La Rochelle</a>
  <ul class="collapse">
  <li><a href="#emplois-résidents-au-carreau-inspire-200m" id="toc-emplois-résidents-au-carreau-inspire-200m" class="nav-link" data-scroll-target="#emplois-résidents-au-carreau-inspire-200m"><span class="toc-section-number">3.1.1</span>  Emplois, résidents au carreau Inspire 200m</a></li>
  <li><a href="#calcul-des-distances-par-mode" id="toc-calcul-des-distances-par-mode" class="nav-link" data-scroll-target="#calcul-des-distances-par-mode"><span class="toc-section-number">3.1.2</span>  Calcul des distances par mode</a></li>
  <li><a href="#sec-ajust" id="toc-sec-ajust" class="nav-link" data-scroll-target="#sec-ajust"><span class="toc-section-number">3.1.3</span>  Ajustement de MEAPS sur MOBPRO</a></li>
  <li><a href="#scénarios-localisation-de-lemploi" id="toc-scénarios-localisation-de-lemploi" class="nav-link" data-scroll-target="#scénarios-localisation-de-lemploi"><span class="toc-section-number">3.1.4</span>  Scénarios “localisation de l’emploi”</a></li>
  <li><a href="#scénarios-transport-en-commun" id="toc-scénarios-transport-en-commun" class="nav-link" data-scroll-target="#scénarios-transport-en-commun"><span class="toc-section-number">3.1.5</span>  Scénarios “transport en commun”</a></li>
  </ul></li>
  </ul>
</nav>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title d-none d-lg-block"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Application à la Rochelle</span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    <div>
    <div class="quarto-title-meta-heading">Modifié</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">3 février 2023</p>
    </div>
  </div>
    
  </div>
  

</header>

<section id="sec-rochelle" class="level2 page-columns page-full" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="sec-rochelle"><span class="header-section-number">3.1</span> Une application à l’agglomération de La Rochelle</h2>
<p>Nous proposons ici une première application de MEAPS à l’agglomération de la Rochelle. Cette application est issue d’un travail de quantification de scénarios de politiques publiques visant à réduire l’empreinte carbone associée aux mobilités quotidiennes et au secteur résidentiel. La quantification demande à la fois de produire une cartographie très fine des émissions, en procédant par interpolation à partir de données plus macroscopiques mesurées par ailleurs et d’être en mesure de produire des évaluations des différences d’émissions localement et à l’échelle du territoire selon les différents scénarios. Nous présentons ici deux familles de scénarios pour lesquelles MEAPS a été mobilisé :</p>
<ul>
<li><p>Des scénarios de localisation de l’emploi : nous projetons la distribution des trajets en utilisant MEAPS sur deux structures spatiales de l’emploi différentes, tout en conservant la même quantité d’emploi globale. La différence entre les kilomètres parcourus suivant les différents modes dans les deux scénarios permet d’évaluer l’impact de la localisation, en distinguant la contribution du changement modal, la contribution des changements de distance pure (à mode et flux carreaux à carreaux inchangés) et la contribution des changements de flux.</p></li>
<li><p>Des scénarios de modification de la structure du réseau de transport. Le principe est identique à celui pour la localisation de l’emploi. C’est la matrice des distances et des temps qui est modifiée par une modification des infrastructures de transports (par exemple une ligne de bus en plus). Cette matrice de distance différente induit des temps de trajet plus petits mais uniquement pour le mode transport en commun. Elle induit un changement modal (plus de transport en commun, moins des autres modes) et enfin conduit à un changement des rangs des opportunités et donc une redistribution des flux de carreau à carreau.</p></li>
</ul>
<p>Dans les deux familles de scénarios, les simulations par MEAPS permettent de construire un contrefactuel et des alternatives à un niveau fin, croisant la localisation au carreau 200m pour les résidences (5 456 carreaux pour la Rochelle et le périmètre du SCOT) et les opportunités (6 326 carreaux dans le périmètre de 33km autour de l’agglomération de la Rochelle), soit 34,5 millions de flux et de modes. L’agrégation de ces informations est alors possible à des niveaux plus généraux pour analyser les impacts. La conversion des kilomètres ou des minutes en émissions de CO<sub>2</sub> pour la voiture est faite en appliquant des coefficients de conversion conventionnels, ce qui permet d’étendre les indicateurs au champ des émissions de gaz à effet de serre.</p>
<section id="emplois-résidents-au-carreau-inspire-200m" class="level3 page-columns page-full" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="emplois-résidents-au-carreau-inspire-200m"><span class="header-section-number">3.1.1</span> Emplois, résidents au carreau Inspire 200m</h3>
<div class="page-columns page-full"><p>La carte de la zone considéré est représentée sur la <a href="#fig-zoneslr">figure&nbsp;<span>3.1</span></a>. L’analyse est limitée aux résidents du périmètre du Schéma de COhérence Territoriale (SCOT) et considère les emplois dans un rayon 33 kilomètres autour de lieux de résidence. Cette carte est construite à partir des données carroyées de l’INSEE <span class="citation" data-cites="C200">INSEE (<a href="references.html#ref-C200" role="doc-biblioref">2022b</a>)</span> à la résolution du carreau 200m Inspire<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. Nous ajoutons à ces données la localisation de l’emploi sur la même grille en utilisant les fichiers fonciers et les données d’emplois localisés de <span class="citation" data-cites="MOBPRO">INSEE (<a href="references.html#ref-MOBPRO" role="doc-biblioref">2022a</a>)</span>. La méthode consiste à imputer par code NAF les emplois de chaque commune selon <span class="citation" data-cites="MOBPRO">INSEE (<a href="references.html#ref-MOBPRO" role="doc-biblioref">2022a</a>)</span> aux surfaces professionnelles à la parcelle issues des fichiers fonciers. Cela permet ensuite de localiser au carreau 200m les emplois. Cette méthode est assez grossière, puisqu’en particulier la ratio personne/surface n’est pas constant d’une entreprise à l’autre, mais elle fournit une bonne première approximation d’autant que l’extrapolation ne dépasse pas l’échelle de la commune. Elle est en tout cas très supérieure à une imputation uniforme.</p><div class="no-row-height column-margin column-container"><li id="fn1"><p><sup>1</sup>&nbsp;INfrastructure for SPatial InfoRmation in Europe est depuis 2007 une directive pour la production de données spatialisées. Inspire définit une grille de carroyage et son système de projection harmonisée. C’est ce qui suit l’INSEE dans la diffusion des données carroyées. Voir https://inspire-geoportal.ec.europa.eu pour la définition de la grille et des jeux de données.</p></li></div></div>
<div class="cell page-columns page-full">
<div class="cell-output-display page-columns page-full">
<div id="fig-zoneslr" class="quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="output/popemp.png" class="img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption class="figure-caption margin-caption">figure&nbsp;3.1: Localisation es emplois et des résidents, zones de la Rochelle. Le périmètre de du SCOT de la Rochelle est indiqué ainsi que les limites administratives des communes et des EPCI le composant. Sources : OSM, Mapbox, IGN, carroyage INSEE 2017, Flores et fichiers fonciers 2018</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="calcul-des-distances-par-mode" class="level3 page-columns page-full" data-number="3.1.2">
<h3 data-number="3.1.2" class="anchored" data-anchor-id="calcul-des-distances-par-mode"><span class="header-section-number">3.1.2</span> Calcul des distances par mode</h3>
<p>Un ingrédient important de l’analyse du territoire est la prise en compte des distances entre chaque paire possible résidence/emploi. Contrairement à l’analyse synthétique, nous ne nous contentons pas de la distance euclidienne.</p>
<p>Pour ce faire nous calculons à partir d’un calculateur d’itinéraire (R<sup>5</sup> de Conveyal <span class="citation" data-cites="conway2017 conway2018 conway2019">(<a href="references.html#ref-conway2017" role="doc-biblioref">Conway, Byrd, et Linden 2017</a>; <a href="references.html#ref-conway2018" role="doc-biblioref">Conway, Byrd, et Van Eggermond 2018</a>; <a href="references.html#ref-conway2019" role="doc-biblioref">Conway et Stewart 2019</a>)</span> en utilisant le package R5R <span class="citation" data-cites="r5r-2">(<a href="references.html#ref-r5r-2" role="doc-biblioref">Pereira et al. 2021</a>)</span> les distances et surtout les temps de transport pour quatre modes (voiture, vélo, transport en commun, marche à pied). Les temps de transport calculés pour chaque paire de carreaux de résidence et d’emploi, en retenant le centre des carreaux, tiennent compte des différentes contraintes de circulation (vitesses limites pour la voiture, sens de circulation, pénalité pour changement de direction, accès autorisé ou restreint suivant le mode, stress à vélo). Concernant les déplacements en voiture, nous ne prenons pas en compte à ce stade la congestion. Concernant les transports en commun, le niveau de détail est assez grand, puisque les fréquences de voyages ainsi que les correspondances sont prises en compte. Dans certaines villes, il est possible d’accéder à une information sur les temps de parcours effectifs (mesurant ainsi la congestion ou la disponibilité du réseau) en complément des horaires théoriques. Ces informations ne sont pas disponible pour l’agglomération de la Rochelle et donc cette possibilité n’est pas explorée. L’accès aux données GTFS impose quelques limites, comme par exemple la non prise en compte des réseaux scolaires ou d’autres réseaux locaux ou privés non publiés sous ce format. La modification du réseau de transport comme l’ouverture d’une ligne ou l’accroissement de fréquence est pris en compte en modifiant la matrice des distances et temps par mode entre chaque carreau de résidence et chaque carreau de destination. Dans le cas de l’agglomération de la Rochelle, le nombre de paires calculés est de l’ordre de 16 millions.</p>
<p>A partir des temps de trajets par mode, nous appliquons un modèle de choix discret, <em>Random Utility Model</em> (RUM) à la McFadden, estimé sur l’enquête mobilité des personnes 2019 <span class="citation" data-cites="MOBPERS">SDES (<a href="references.html#ref-MOBPERS" role="doc-biblioref">2021</a>)</span> en utilisant les données de mobilités professionnelles <span class="citation" data-cites="MOBPRO">INSEE (<a href="references.html#ref-MOBPRO" role="doc-biblioref">2022a</a>)</span> pour caler les flux commune à commune. L’estimation de ce modèle est détaillée dans un autre document (référence à insérer).</p>
<p>Les distances entre chaque paire de cases permettent de calculer un indicateur d’accessibilité qui joue un rôle central dans le modèle radiatif, et donc dans MEAPS, en remplaçant la distance par la somme des opportunités en deçà d’un seuil de temps. La carte de la <a href="#fig-4access">figure&nbsp;<span>3.2</span></a> représente les temps pour accéder à 10 000 emplois en utilisant différents modes de transport.</p>
<div class="cell page-columns page-full">
<div class="cell-output-display page-columns page-full">
<div id="fig-4access" class="quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="output/access_4modes.png" class="img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption class="figure-caption margin-caption">figure&nbsp;3.2: Temps d’accès à 10 000 emplois. Pour chaque carreau de résidence, on détermine le temps minimal pour atteindre au moins 10 000 emplois suivant l’un des quatre modes considéré. Cette mesure remplace la distance dans le modèle radiatif. Calcul des auteurs. Sources : OSM, Mapbox, IGN, Conveyal R5, carroyage INSEE 2017, Flores et fichiers fonciers 2018</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Les courbes d’accessibilité de la <a href="#fig-comaccess">figure&nbsp;<span>3.3</span></a> sont construite en prenant la moyenne par commune de résidence des temps d’accès pour les différents seuils d’emplois. C’est cette courbe qui découle du modèle théorique présenté plus haut (<a href="theorie.html#sec-meaps"><span>Section&nbsp;1.3</span></a>) et qui détermine les choix individuels de déplacement comme de localisation. Ces courbes font apparaître une propriété propre aux villes littorales : si pour des temps courts ou des moyens de transport peu rapide, l’accès à l’emploi pour des temps courts est maximal à la Rochelle, en revanche, d’autres communes jouissent d’une position plus centrale lorsqu’on accepte des temps de trajets supérieurs à 30 minutes en voiture.</p>
<div class="cell page-columns page-full">
<div class="cell-output-display page-columns page-full">
<div id="fig-comaccess" class="quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="output/access_par_com.png" class="img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption class="figure-caption margin-caption">figure&nbsp;3.3: Courbe du temps d’accès aux emplois. Pour chaque commune, on calcule la médianne, pondérée par le nombre d’habitants par carreau, du temps d’accès à différents seuils d’emplois. Cela permet de caractériser les communes par leur accessibilité à l’emploi, une mesure plus pertinente de la ‘distance à l’emploi’. Calcul des auteurs. Sources : OSM, Mapbox, IGN, Conveyal R5, carroyage INSEE 2017, Flores et fichiers fonciers 2018</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="sec-ajust" class="level3 page-columns page-full" data-number="3.1.3">
<h3 data-number="3.1.3" class="anchored" data-anchor-id="sec-ajust"><span class="header-section-number">3.1.3</span> Ajustement de MEAPS sur MOBPRO</h3>
<p>La construction de la matrice de distance permet d’utiliser MEAPS pour déduire les flux carreau à carreau. Mais le fichier détail du recensement et son volet mobilités professionnelles nous donnent une information supplémentaire que nous pouvons utiliser pour calibrer au plus près des données MEAPS. Les mobilités professionnelles décrivent pour chaque paire de commune résidence-emploi les flux de mobilités professionnelles (de nombreuses paires de communes ont des flux nuls). Cette information est équivalente à celle produite par MEAPS mais agrégée au niveau communal. Une première stratégie de calage de MEAPS est d’affecter aux probabilités d’absorption un facteur correcteur pour reproduire le plus fidèlement possible les flux agrégés de <span class="citation" data-cites="MOBPRO">INSEE (<a href="references.html#ref-MOBPRO" role="doc-biblioref">2022a</a>)</span>. Cette approche permet ensuite d’utiliser MEAPS sur les données <span class="citation" data-cites="MOBPRO">INSEE (<a href="references.html#ref-MOBPRO" role="doc-biblioref">2022a</a>)</span> pour réaliser une interpolation infra-communale des déplacements, au carreau 200m. En accédant à ce niveau de détail, nous pouvons ensuite mobiliser la méthode de calcul des distances et des temps de trajets à une échelle fine pour produire des différences au carreau 200m. Dans une autre approche, plus parcimonieuse, on pourrait limiter le nombre de paramètres estimés pour MEAPS, afin d’une apprécier la qualité prédictive et le comparer à une autre approche. Nous détaillerons cette autre approche dans un futur document.</p>
<p>La modification des probabilités d’absorption est faite par l’ajout d’un facteur correcteur exprimé en “chance”, c’est-à-dire que la probabilité modifiée l’est par la formule suivante où <span class="math inline">\omicron_{i,j}</span> est un nombre entre <span class="math inline">0</span> et <span class="math inline">+\infty</span> et <span class="math inline">i,j</span> indexent les communes de départ et d’arrivée avec <span class="math inline">c_a = p_a/(1-p_a)</span> :</p>
<p><span id="eq-odd"><span class="math display">
\tilde{p}_a = \frac{c_a \times \omicron_{i,j}} {1+c_a \times \omicron_{i,j}}
\tag{3.1}</span></span></p>
<p>A ce stade nous utilisons un algorithme naïf pour trouver une solution au problème posé. Nous calculons l’<em>odd-ratio</em> entre le résultat d’une simulation associée à un ensemble d’<span class="math inline">\omicron_{i,j}</span> et celui défini par les données observées de <span class="citation" data-cites="MOBPRO">INSEE (<a href="references.html#ref-MOBPRO" role="doc-biblioref">2022a</a>)</span> en utilisant la formule suivante où <span class="math inline">\beta</span> est un paramètre d’amortissement inférieur à 1 et positif et <span class="math inline">k</span> indexe les itérations :</p>
<p><span id="eq-algest"><span class="math display">
\omicron^k_{i,j} = (\frac{\tilde{p}^k_a/(1-\tilde{p}^k_a)}{
p^{mobpro}_a/(1-p^{mobpro}_a)})^\beta \times \omicron^{k-1}_{i,j}
\tag{3.2}</span></span></p>
<p>Nous modifions alors les <span class="math inline">\omicron_{i,j}</span> en fonction des écarts observés. Cela conduit à chercher un point fixe. Nous calculons ensuite un critère d’ajustement à partir de l’entropie relative de Kullback-Leibler <span class="citation" data-cites="kullback1951">(<a href="references.html#ref-kullback1951" role="doc-biblioref">Kullback et Leibler 1951</a>)</span>. L’entropie relative est définie pour deux distributions de probabilités <span class="math inline">p</span> et <span class="math inline">q</span> comme suit (dans le cas discret, le cas continu se généralise aisément) :</p>
<p><span id="eq-kl"><span class="math display">
KL(p,q) = \sum_{i}p_i \times log(p_i/q_i)
\tag{3.3}</span></span></p>
<p>Cette mesure ressemble à une distance, mais n’est pas symétrique et ne vérifie pas l’inégalité triangulaire. Elle s’interprète dans le cadre de la théorie de l’information comme la quantité relative d’information supplémentaire nécessaire pour exprimer <span class="math inline">q</span> à partir de <span class="math inline">p</span>. En suivant <span class="citation" data-cites="colincameron1997">Colin Cameron et Windmeijer (<a href="references.html#ref-colincameron1997" role="doc-biblioref">1997</a>)</span> on peut construire une mesure de la qualité de l’ajustement <span class="math inline">R_{KL}^2</span> de la façon suivante, où <span class="math inline">\hat{q}</span> et <span class="math inline">q_0</span> sont deux distributions respectivement estimée et de référence que l’on compare à <span class="math inline">p</span> :</p>
<p><span id="eq-r2kl"><span class="math display">
R_{KL}^2 = 1 - \frac{KL(p,\hat{q})}{KL(p, q_0)}
\tag{3.4}</span></span></p>
<p>La distribution de référence est choisie comme une distribution uniforme, par analogie avec le calcul de la variance dans un <span class="math inline">R^2</span> habituel où l’on régresse sur une constante. On écrit :</p>
<p><span id="eq-klent"><span class="math display">
\begin{aligned}
KL(p,q_{ref}) &amp;{}= \sum_{i}p_i \times log(p_i/unif) \\&amp;{}= \sum_i p_i \times log(p_i) + log(N)
\end{aligned}
\tag{3.5}</span></span></p>
<p>qui n’est autre que l’entropie de la distribution <span class="math inline">p</span> à une constante près (<span class="math inline">N</span> est le nombre de résidents actifs ou d’emplois).</p>
<p>L’algorithme employé devra être affiné dans le futur afin de permettre une descente de gradient qui permet de minimiser l’entropie relative. L’algorithme naïf permet de réduire cette entropie relative sans assurer qu’elle est minimale. Nous utiliserons l’algorithme naïf pour explorer la possibilité d’ajuster MEAPS sur un jeu de données. Cet algorithme a été utilisé avec différentes contraintes sur les paramètres. Le <a href="#tbl-meapsR2">tableau&nbsp;<span>3.1</span></a> indique la qualité de l’ajustement obtenu dans ces différentes configurations. La première est celle où les probabilités d’absorption sont déterminées uniquement par les fuites par commune de résidence. C’est la configuration la plus parcimonieuse en termes de paramètres et qui sert de référence. Le <span class="math inline">R^2_{KL}</span> vaut 89.1% ce qui est déjà un ajustement élevé. La seconde configuration est celle où l’on ajuste des <span class="math inline">\omicron_{i,j}</span> uniquement pour les termes diagonaux (<span class="math inline">i=j</span>). Cette configuration ajuste donc un <em>odd-ratio</em> pour les résidents qui travaillent dans leur commune de résidence. Dans un certain nombre de communes, cet ajustement conduit à augmenter la probabilité d’absorption interne (<a href="#fig-carteodd">figure&nbsp;<span>3.7</span></a>), ce qui indique que le choix de résidence n’est pas indépendant de celui d’activité. Pour la commune la plus importante (la Rochelle), en revanche, l’<em>odd-ratio</em> <span class="math inline">\omicron_{17300, 17300}</span> est proche de 1. Les deux configurations suivantes laissent beaucoup plus de degrés de liberté en estimant des <span class="math inline">\omicron_{i,j}</span> librement. La première de ces deux configurations limite les <span class="math inline">\omicron_{i,j}</span> estimés à ceux représentant un total cumulé des flux mesurés par <span class="citation" data-cites="MOBPRO">INSEE (<a href="references.html#ref-MOBPRO" role="doc-biblioref">2022a</a>)</span> égal à 98% ce qui représente un peu moins de 2 000 <span class="math inline">\omicron_{i,j}</span>. La seconde configuration estime tous les <span class="math inline">\omicron_{i,j}</span> sans limite (soit 15 120 paramètres pour 72 communes de résidence et 210 communes d’activité).</p>
<div class="cell page-columns page-full">
<div class="cell-output-display page-columns page-full">
<div id="tbl-meapsR2" class="anchored page-columns page-full">

<div id="loieziacvd" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;" class="page-columns page-full">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

:where(#loieziacvd) .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

:where(#loieziacvd) .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

:where(#loieziacvd) .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

:where(#loieziacvd) .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

:where(#loieziacvd) .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

:where(#loieziacvd) .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

:where(#loieziacvd) .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

:where(#loieziacvd) .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

:where(#loieziacvd) .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

:where(#loieziacvd) .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

:where(#loieziacvd) .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

:where(#loieziacvd) .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

:where(#loieziacvd) .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

:where(#loieziacvd) .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

:where(#loieziacvd) .gt_from_md > :first-child {
  margin-top: 0;
}

:where(#loieziacvd) .gt_from_md > :last-child {
  margin-bottom: 0;
}

:where(#loieziacvd) .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

:where(#loieziacvd) .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#loieziacvd) .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

:where(#loieziacvd) .gt_row_group_first td {
  border-top-width: 2px;
}

:where(#loieziacvd) .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#loieziacvd) .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

:where(#loieziacvd) .gt_first_summary_row.thick {
  border-top-width: 2px;
}

:where(#loieziacvd) .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

:where(#loieziacvd) .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#loieziacvd) .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

:where(#loieziacvd) .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

:where(#loieziacvd) .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

:where(#loieziacvd) .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

:where(#loieziacvd) .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#loieziacvd) .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

:where(#loieziacvd) .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#loieziacvd) .gt_left {
  text-align: left;
}

:where(#loieziacvd) .gt_center {
  text-align: center;
}

:where(#loieziacvd) .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

:where(#loieziacvd) .gt_font_normal {
  font-weight: normal;
}

:where(#loieziacvd) .gt_font_bold {
  font-weight: bold;
}

:where(#loieziacvd) .gt_font_italic {
  font-style: italic;
}

:where(#loieziacvd) .gt_super {
  font-size: 65%;
}

:where(#loieziacvd) .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

:where(#loieziacvd) .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

:where(#loieziacvd) .gt_indent_1 {
  text-indent: 5px;
}

:where(#loieziacvd) .gt_indent_2 {
  text-indent: 10px;
}

:where(#loieziacvd) .gt_indent_3 {
  text-indent: 15px;
}

:where(#loieziacvd) .gt_indent_4 {
  text-indent: 20px;
}

:where(#loieziacvd) .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id=""></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="N(p<sub>f,i</sub>)">N(p<sub>f,i</sub>)</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="N(o<sub>i,j</sub>)">N(o<sub>i,j</sub>)</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="R<sub>KL</sub><sup>2</sup>">R<sub>KL</sub><sup>2</sup></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="config" class="gt_row gt_left">Fuite par commune de résidence</td>
<td headers="n_fuite" class="gt_row gt_right">72</td>
<td headers="n_params" class="gt_row gt_right">0</td>
<td headers="r2kl" class="gt_row gt_right">89.1%</td></tr>
    <tr><td headers="config" class="gt_row gt_left">Fuite et diagonale</td>
<td headers="n_fuite" class="gt_row gt_right">72</td>
<td headers="n_params" class="gt_row gt_right">72</td>
<td headers="r2kl" class="gt_row gt_right">94.3%</td></tr>
    <tr><td headers="config" class="gt_row gt_left">Fuite et 90% des flux</td>
<td headers="n_fuite" class="gt_row gt_right">72</td>
<td headers="n_params" class="gt_row gt_right">729</td>
<td headers="r2kl" class="gt_row gt_right">95.9%</td></tr>
    <tr><td headers="config" class="gt_row gt_left">Fuite et 99% des flux</td>
<td headers="n_fuite" class="gt_row gt_right">72</td>
<td headers="n_params" class="gt_row gt_right">1 928</td>
<td headers="r2kl" class="gt_row gt_right">98.3%</td></tr>
    <tr><td headers="config" class="gt_row gt_left">Fuite et 100% des flux</td>
<td headers="n_fuite" class="gt_row gt_right">72</td>
<td headers="n_params" class="gt_row gt_right">15 120</td>
<td headers="r2kl" class="gt_row gt_right">99.0%</td></tr>
  </tbody>
  
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="4"> L'ajustement de MEAPS est réalisé par l'algorithme décrit dans le texte. Le nombre de paramètres estimés est égal à la somme de la colonne N(p<sub>f,i</sub>) et de la colonne N(o<sub>i,j</sub>).</td>
    </tr>
  </tfoot>
</table>
<div class="quarto-table-caption margin-caption">tableau&nbsp;3.1:  Ajustement de MEAPS </div></div>
</div>
</div>
</div>
<p>la <a href="#fig-actvsfit">figure&nbsp;<span>3.4</span></a> représente les flux observés et estimés pour les différentes configurations du <a href="#tbl-meapsR2">tableau&nbsp;<span>3.1</span></a>. Le gain à estimer les <span class="math inline">\omicron_{i,i}</span> diagonaux, pondérant les flux allant d’une commune de résidence vers elle même est assez élevé, faisant passer le <span class="math inline">R^2_{KL}</span> de 89.1% à 94.3% et réduisant les écarts entre flux observé et flux estimé comme le montrent les deux panneaux supérieurs de la <a href="#fig-actvsfit">figure&nbsp;<span>3.4</span></a>. L’ajout de paramètres supplémentaires ne fait pas gagner beaucoup plus d’autant que les écarts pour les flux marginaux ne sont pas tant réduit que ça. La limite de l’algorithme naïf apparaît ici, puisque le modèle complètement saturé n’ajuste pas totalement la distribution. Différents détails de l’algorithme peuvent l’expliquer, notamment la censure des <em>odd-ratio</em> trop faibles (&lt;0.0001) ou trop importants (&gt;10000) ou la prise en compte des flux nuls. Au-delà de cet argument, il est probable que pour converger vers un ajustement plus strict, il serait nécessaire de calculer la matrice des quasi dérivées des flux par rapport aux <span class="math inline">\omicron_{i,j}</span>.</p>
<div class="page-columns page-full"><p>Mais le coût peut être très élevé puisque cette matrice (calculée dans la partie synthétique dans un cas simple) est d’une taille considérable (15 120 <span class="math inline">\times</span> 15 120 coefficients), surtout si l’on prend en compte que le calcul de chaque terme prend quelques dizaine de secondes<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>.</p><div class="no-row-height column-margin column-container"><li id="fn2"><p><sup>2</sup>&nbsp;Autour de mille années de vCPU…</p></li></div></div>
<div class="cell page-columns page-full">
<div class="cell-output-display page-columns page-full">
<div id="fig-actvsfit" class="quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="output/estmeaps.png" class="img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption class="figure-caption margin-caption">figure&nbsp;3.4: La figure présente pour chaque configuration d’estimation le flux observé (axe des x) et le flux estimé (axe des y) en bleu lorsque o<sub>i,j</sub> est estimé et en rouge lorsque o<sub>i,j</sub> n’est pas estimé (les fuites sont toujours utilisées). La valeur de référence est répétée dans chaque panneau en gris clair.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="page-columns page-full"><p>Pour les 20 plus grandes communes de l’agglomération de la Rochelle – qui comptent plus de 1 000 résidents en activité – on peut représenter les <em>odd-ratios,</em> construits comme le ratio des chances (<span class="math inline">p_{a,i,j}/(1-p_{a,i,j}</span>)) estimées dans la configuration 100% des flux par rapport aux chances calculées dans le cas où tous les <span class="math inline">\omicron_{i,j}</span> sont égaux à 1, en fonction de la distance de la commune de destination à la commune de résidence<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>. Ce diagramme, analogue à un spectre, peut aussi être constuit par commune de destination, la distance <span class="math inline">d</span> étant la distance aux différentes communes de résidence <a href="#fig-spectreE">figure&nbsp;<span>3.6</span></a>. L’élément le plus frappant est que les <em>odd-ratios</em> de <span class="math inline">i</span> à <span class="math inline">i</span> sont généralement supérieur à 1 (<a href="#fig-spectreR">figure&nbsp;<span>3.5</span></a>), à l’exception de la commune de la Rochelle. Il n’émerge pas de structure particulière par rapport à la distance, si ce n’est des <em>odd-ratios</em> élevés pour des distances importantes</p><div class="no-row-height column-margin column-container"><li id="fn3"><p><sup>3</sup>&nbsp;La distance est construite comme la distance moyenne pondérée entre les résidents de la commune de départ et les emplois de la commune d’arrivée. La pondération est le produit des emplois et des résidents pour chaque paire, normalisé à 1.</p></li></div></div>
<div class="cell-output-display page-columns page-full">
<div id="fig-spectreR" class="quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="output/spectre effectif par COMMUNE 100.png" class="img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption class="figure-caption margin-caption">figure&nbsp;3.5: La figure représente pour les 20 plus grandes communes de l’agglomération de la Rochelle les odd-ratios estimés (configuration 100% des flux) en fonction de la distance entre cette commune et les communes où travaillent les résidents. Les points marqués d’un petit point blancs sont les emplois situés hors du périmètre du SCoT.</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell page-columns page-full">
<div class="cell-output-display page-columns page-full">
<div id="fig-spectreE" class="quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="output/spectre effectif par DCLT 100.png" class="img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption class="figure-caption margin-caption">figure&nbsp;3.6: La figure représente pour les 13 plus grandes communes d’emplois du pérmiètre géographique (33 km autour de l’agglomération de la Rochelle) les odd-ratios estimés (configuration 100% des flux) en fonction de la distance entre cette commune et les communes où résident les travailleurs de la commune.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>La <a href="#fig-carteodd">figure&nbsp;<span>3.7</span></a> permet de préciser la valeur élevée des <em>odd-ratios</em> pour les flux internes. Les communes où sont localisés de nombreux emplois ont un <em>odd-ratio</em> plutôt plus faible alors qu’ils sont estimés plus élevés dans les communes plus petites et moins desservies. Pour les différentes procédure d’estimation et donc différents nombres de paramètres estimés, on observe une structure similaire dans la répartition géographique des <em>odd-ratio</em>, ce qui suggère que les <em>odd-ratios</em> estimés contiennent de l’information.</p>
<p>Un <em>odd-ratio</em> élevé indique que les flux internes sont plus élevés que dans le scénario de référence. Cela indique probablement un choix de résidence en lien avec l’emploi occupé en privilégiant la commune d’activité pour la résidence (ou l’inverse). Le spectre résident en fonction de la distance indique que ce phénomène, s’il est une hypothèse à très faible distance, ne persiste pas en dehors de la commune de résidence. En revanche, la <a href="#fig-spectreE">figure&nbsp;<span>3.6</span></a> suggère que dans certaines communes, notamment Surgères, on observe des <em>odd-ratios</em> supérieurs à 1 pour les des distances faibles, ce qui tend à indiquer que les habitants des communes alentours privilégient Surgères comme lieu d’emploi.</p>
<p>A ce stade, les observations sont limitées par le faible nombre de communes modélisées, mais on peut espérer que l’analyse des <em>odd-ratios</em> estimés pourra servir à caractériser les communes en fonction des choix de résidence et d’emploi. En multipliant cette analyse pour d’autres territoires, l’information apportée par les <em>odd-ratio</em> pourra être inférée. Il sera aussi possible de confronter ces éléments à d’autres variables, comme le prix de l’immobilier, les loyers résidentiels ou commerciaux, la densité d’emploi.</p>
<p>Une autre approche empirique serait de définir une forme fonctionnelle pour les <em>odd-ratio</em> en paramétrant cette forme fonctionnelle de façon parcimonieuse. On pourra alors tester des hypothèses et tenter d’extraire une information de la structure des <em>odd-ratios.</em> Une autre approche est de procéder à une analyse de régression multivariée sur les <em>odd-ratios</em> estimés.<br>
</p>
<div class="cell page-columns page-full">
<div class="cell-output-display page-columns page-full">
<div id="fig-carteodd" class="quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="output/toutes configs odds effectifs.png" class="img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption class="figure-caption margin-caption">figure&nbsp;3.7: Chaque cercle indique les odd-ratio estimés dans la diagonale (100% des flux). Les diamètres des cercles sont proportionels aux flux internes (de i à i).</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="scénarios-localisation-de-lemploi" class="level3 page-columns page-full" data-number="3.1.4">
<h3 data-number="3.1.4" class="anchored" data-anchor-id="scénarios-localisation-de-lemploi"><span class="header-section-number">3.1.4</span> Scénarios “localisation de l’emploi”</h3>
<p>Le Schéma de Cohérence Territorial (SCoT) est un document de planification, établi et voté par les élus des communes composant le territoire et soumis à validation de l’État. Il défini, entre autres, des zones de développement économique, urbaines et des espaces naturels. C’est la loi SRU relative à la Solidarité et au Renouvellement Urbains du 13 décembre 2000 qui l’a défini et les contours en ont été modifiés au cours des dernières années.</p>
<p>Le schéma n’est pas qu’indicatif puisqu’il est opposable. En ce qui concerne le développement de l’emploi, la création de zones d’activité est rendue possible par le SCoT, mais la réalisation effective des créations d’emploi et surtout leur localisation nette des déplacements d’autres emplois découle des décisions de l’ensemble des acteurs et donc et donc de causalités diverses et variées. Nous évaluons ici des scénarios comptatible avec le SCoT sans pour autant nous prononcer quant à leur réalisme ou leur probabilité d’occurrence. Ainsi, nous analysons les localisations proposées à emploi total constant, c’est-à-dire vues comme des relocalisations de l’emploi vers les zones d’activités depuis leur localisation actuelle.</p>
<div class="page-columns page-full"><p>La construction de cette analyse impose donc de connaître précisément la localisation de l’emploi, ce que nous réalisons par une imputation au carreau INSPIRE 200m à partir des données d’emploi par commune. Nous calons alors MEAPS sur ces données ainsi que sur les données de mobilité professionnelles issues du recensement<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> et publiées par l’INSEE. Ces données donnent les lieux habituels de travail (à la commune) pour les différents résidents (d’une commune) ainsi que les flux correspondant entre paires de communes.</p><div class="no-row-height column-margin column-container"><li id="fn4"><p><sup>4</sup>&nbsp;https://www.insee.fr/fr/information/2383243</p></li></div></div>
<div class="page-columns page-full"><p>La construction de cette analyse impose donc de connaître précisément la localisation de l’emploi, ce que nous réalisons par une imputation au carreau INSPIRE 200m à partir des données d’emploi par commune. Nous calons alors MEAPS sur ces données ainsi que sur les données de mobilité professionnelles issues du recensement<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> et publiées par l’INSEE. Ces données donnent les lieux habituels de travail (à la commune) pour les différents résidents (d’une commune) ainsi que les flux correspondant entre paires de communes.</p><div class="no-row-height column-margin column-container"><li id="fn5"><p><sup>5</sup>&nbsp;Autour de mille années de vCPU…</p></li></div></div>
<ul>
<li>Une fois MEAPS calé sur ces données, nous pouvons analyser des scénarios de déplacement des emplois et en déduire les conséquences en trajets, mode de transport et donc émissions de CO<sub>2</sub> associé</li>
</ul>
</section>
<section id="scénarios-transport-en-commun" class="level3" data-number="3.1.5">
<h3 data-number="3.1.5" class="anchored" data-anchor-id="scénarios-transport-en-commun"><span class="header-section-number">3.1.5</span> Scénarios “transport en commun”</h3>
<p>L’analyse du territoire ne repose pas seulement sur la localisation de l’emploi, mais aussi sur une prise en compte détaillée des possibilités de transport.</p>


<!-- -->

<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography" style="display: none">
<div id="ref-colincameron1997" class="csl-entry" role="doc-biblioentry">
Colin Cameron, A., et Frank A. G. Windmeijer. 1997. <span>«&nbsp;An R-Squared Measure of Goodness of Fit for Some Common Nonlinear Regression Models&nbsp;»</span>. <em>Journal of Econometrics</em> 77 (2): 329‑42. <a href="https://doi.org/10.1016/s0304-4076(96)01818-0">https://doi.org/10.1016/s0304-4076(96)01818-0</a>.
</div>
<div id="ref-conway2017" class="csl-entry" role="doc-biblioentry">
Conway, Matthew Wigginton, Andrew Byrd, et Marco van der Linden. 2017. <span>«&nbsp;Evidence-Based Transit and Land Use Sketch Planning Using Interactive Accessibility Methods on Combined Schedule and Headway-Based Networks&nbsp;»</span>. <em>Transportation Research Record: Journal of the Transportation Research Board</em> 2653 (1): 45‑53. <a href="https://doi.org/10.3141/2653-06">https://doi.org/10.3141/2653-06</a>.
</div>
<div id="ref-conway2018" class="csl-entry" role="doc-biblioentry">
Conway, Matthew Wigginton, Andrew Byrd, et Michael Van Eggermond. 2018. <span>«&nbsp;Accounting for uncertainty and variation in accessibility metrics for public transport sketch planning&nbsp;»</span>. <em>Journal of Transport and Land Use</em> 11 (1). <a href="https://doi.org/10.5198/jtlu.2018.1074">https://doi.org/10.5198/jtlu.2018.1074</a>.
</div>
<div id="ref-conway2019" class="csl-entry" role="doc-biblioentry">
Conway, Matthew Wigginton, et Anson F. Stewart. 2019. <span>«&nbsp;Getting Charlie Off the MTA: A Multiobjective Optimization Method to Account for Cost Constraints in Public Transit Accessibility Metrics&nbsp;»</span>. <em>International Journal of Geographical Information Science</em> 33 (9): 1759‑87. <a href="https://doi.org/10.1080/13658816.2019.1605075">https://doi.org/10.1080/13658816.2019.1605075</a>.
</div>
<div id="ref-MOBPRO" class="csl-entry" role="doc-biblioentry">
INSEE. 2022a. <span>«&nbsp;Mobilités professionnelles en 2019 : déplacements domicile - lieu de travail Recensement de la population - Base flux de mobilité&nbsp;»</span>. <a href="https://www.insee.fr/fr/statistiques/6454112" class="uri">https://www.insee.fr/fr/statistiques/6454112</a>.
</div>
<div id="ref-C200" class="csl-entry" role="doc-biblioentry">
———. 2022b. <span>«&nbsp;Revenus, pauvreté et niveau de vie en 2017 - Données carroyées. Dispositif Fichier localisé social et fiscal (Filosofi)&nbsp;»</span>. <a href="https://www.insee.fr/fr/statistiques/6214811?sommaire=6215217" class="uri">https://www.insee.fr/fr/statistiques/6214811?sommaire=6215217</a>.
</div>
<div id="ref-kullback1951" class="csl-entry" role="doc-biblioentry">
Kullback, S., et R. A. Leibler. 1951. <span>«&nbsp;On Information and Sufficiency&nbsp;»</span>. <em>The Annals of Mathematical Statistics</em> 22 (1): 79‑86. <a href="https://doi.org/10.1214/aoms/1177729694">https://doi.org/10.1214/aoms/1177729694</a>.
</div>
<div id="ref-r5r-2" class="csl-entry" role="doc-biblioentry">
Pereira, Rafael H. M., Marcus Saraiva, Daniel Herszenhut, Carlos Kaue Vieira Braga, et Matthew Wigginton Conway. 2021. <span>«&nbsp;r5r: Rapid Realistic Routing on Multimodal Transport Networks with R5 in R&nbsp;»</span>. <a href="https://doi.org/10.32866/001c.21262">https://doi.org/10.32866/001c.21262</a>.
</div>
<div id="ref-MOBPERS" class="csl-entry" role="doc-biblioentry">
SDES, Ministère de la transition écologique et de la cohésion des territoires. 2021. <span>«&nbsp;EMP 2019 Résultats détaillés de l’enquête mobilité des personnes de 2019&nbsp;»</span>. <a href="https://www.statistiques.developpement-durable.gouv.fr/resultats-detailles-de-lenquete-mobilite-des-personnes-de-2019" class="uri">https://www.statistiques.developpement-durable.gouv.fr/resultats-detailles-de-lenquete-mobilite-des-personnes-de-2019</a>.
</div>
</div>
</section>
</section>


</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copié");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copié");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./simsynth.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">MEAPS : Simulations synthétiques</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./references.html" class="pagination-link">
        <span class="nav-page-text">Références bibliographiques</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Code source</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Application à la Rochelle"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="in">```{r init, include = FALSE}</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>opts_chunk<span class="sc">$</span><span class="fu">set</span>(</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">echo =</span> <span class="cn">FALSE</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">warning =</span> <span class="cn">FALSE</span>,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">message =</span> <span class="cn">FALSE</span>,</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">fig.pos=</span><span class="st">"htb"</span>, </span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">out.extra=</span><span class="st">""</span>,</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">dev=</span><span class="st">"ragg_png"</span>,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">out.width=</span><span class="st">"100%"</span>,</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">fig.showtext=</span><span class="cn">TRUE</span>,</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">cache=</span><span class="cn">FALSE</span>)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ofce)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(showtext)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(markdown)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gt)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>sysfonts<span class="sc">::</span><span class="fu">font_add_google</span>(<span class="st">'Nunito'</span>)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="fu">showtext_opts</span>(<span class="at">dpi =</span> <span class="dv">600</span>)</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="fu">showtext_auto</span>()</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">ofce.background_color =</span> <span class="st">"grey97"</span>)</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">ofce.base_family =</span> <span class="st">"Roboto"</span>)</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">ofce.base_size =</span> <span class="dv">9</span>)</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="fu">## Une application à l'agglomération de La Rochelle {#sec-rochelle}</span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>Nous proposons ici une première application de MEAPS à l'agglomération de la Rochelle.</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>Cette application est issue d'un travail de quantification de scénarios de politiques publiques visant à réduire l'empreinte carbone associée aux mobilités quotidiennes et au secteur résidentiel.</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>La quantification demande à la fois de produire une cartographie très fine des émissions, en procédant par interpolation à partir de données plus macroscopiques mesurées par ailleurs et d'être en mesure de produire des évaluations des différences d'émissions localement et à l'échelle du territoire selon les différents scénarios.</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>Nous présentons ici deux familles de scénarios pour lesquelles MEAPS a été mobilisé :</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Des scénarios de localisation de l'emploi : nous projetons la distribution des trajets en utilisant MEAPS sur deux structures spatiales de l'emploi différentes, tout en conservant la même quantité d'emploi globale.</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>    La différence entre les kilomètres parcourus suivant les différents modes dans les deux scénarios permet d'évaluer l'impact de la localisation, en distinguant la contribution du changement modal, la contribution des changements de distance pure (à mode et flux carreaux à carreaux inchangés) et la contribution des changements de flux.</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Des scénarios de modification de la structure du réseau de transport.</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>    Le principe est identique à celui pour la localisation de l'emploi.</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>    C'est la matrice des distances et des temps qui est modifiée par une modification des infrastructures de transports (par exemple une ligne de bus en plus).</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>    Cette matrice de distance différente induit des temps de trajet plus petits mais uniquement pour le mode transport en commun.</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>    Elle induit un changement modal (plus de transport en commun, moins des autres modes) et enfin conduit à un changement des rangs des opportunités et donc une redistribution des flux de carreau à carreau.</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>Dans les deux familles de scénarios, les simulations par MEAPS permettent de construire un contrefactuel et des alternatives à un niveau fin, croisant la localisation au carreau 200m pour les résidences (5 456 carreaux pour la Rochelle et le périmètre du SCOT) et les opportunités (6 326 carreaux dans le périmètre de 33km autour de l'agglomération de la Rochelle), soit 34,5 millions de flux et de modes.</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>L'agrégation de ces informations est alors possible à des niveaux plus généraux pour analyser les impacts.</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>La conversion des kilomètres ou des minutes en émissions de CO~2~ pour la voiture est faite en appliquant des coefficients de conversion conventionnels, ce qui permet d'étendre les indicateurs au champ des émissions de gaz à effet de serre.</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a><span class="fu">### Emplois, résidents au carreau Inspire 200m</span></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>La carte de la zone considéré est représentée sur la @fig-zoneslr.</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>L'analyse est limitée aux résidents du périmètre du Schéma de COhérence Territoriale (SCOT) et considère les emplois dans un rayon 33 kilomètres autour de lieux de résidence.</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>Cette carte est construite à partir des données carroyées de l'INSEE @C200 à la résolution du carreau 200m Inspire<span class="ot">[^10]</span>.</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>Nous ajoutons à ces données la localisation de l'emploi sur la même grille en utilisant les fichiers fonciers et les données d'emplois localisés de @MOBPRO. La méthode consiste à imputer par code NAF les emplois de chaque commune selon @MOBPRO aux surfaces professionnelles à la parcelle issues des fichiers fonciers.</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>Cela permet ensuite de localiser au carreau 200m les emplois.</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>Cette méthode est assez grossière, puisqu'en particulier la ratio personne/surface n'est pas constant d'une entreprise à l'autre, mais elle fournit une bonne première approximation d'autant que l'extrapolation ne dépasse pas l'échelle de la commune.</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>Elle est en tout cas très supérieure à une imputation uniforme.</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a><span class="ot">[^10]: </span>INfrastructure for SPatial InfoRmation in Europe est depuis 2007 une directive pour la production de données spatialisées.</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>    Inspire définit une grille de carroyage et son système de projection harmonisée.</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>    C'est ce qui suit l'INSEE dans la diffusion des données carroyées.</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>    Voir https://inspire-geoportal.ec.europa.eu pour la définition de la grille et des jeux de données.</span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-zoneslr</span></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-scap: "Localisation des résidents et des emplois"</span></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Localisation es emplois et des résidents, zones de la Rochelle. Le périmètre de du SCOT de la Rochelle est indiqué ainsi que les limites administratives des communes et des EPCI le composant. Sources : OSM, Mapbox, IGN, carroyage INSEE 2017, Flores et fichiers fonciers 2018"</span></span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"output/popemp.png"</span>)</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a><span class="fu">### Calcul des distances par mode</span></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a>Un ingrédient important de l'analyse du territoire est la prise en compte des distances entre chaque paire possible résidence/emploi.</span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a>Contrairement à l'analyse synthétique, nous ne nous contentons pas de la distance euclidienne.</span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>Pour ce faire nous calculons à partir d'un calculateur d'itinéraire (R^5^ de Conveyal <span class="co">[</span><span class="ot">@conway2017; @conway2018; @conway2019</span><span class="co">]</span> en utilisant le package R5R <span class="co">[</span><span class="ot">@r5r-2</span><span class="co">]</span> les distances et surtout les temps de transport pour quatre modes (voiture, vélo, transport en commun, marche à pied).</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>Les temps de transport calculés pour chaque paire de carreaux de résidence et d'emploi, en retenant le centre des carreaux, tiennent compte des différentes contraintes de circulation (vitesses limites pour la voiture, sens de circulation, pénalité pour changement de direction, accès autorisé ou restreint suivant le mode, stress à vélo).</span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a>Concernant les déplacements en voiture, nous ne prenons pas en compte à ce stade la congestion.</span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>Concernant les transports en commun, le niveau de détail est assez grand, puisque les fréquences de voyages ainsi que les correspondances sont prises en compte.</span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a>Dans certaines villes, il est possible d'accéder à une information sur les temps de parcours effectifs (mesurant ainsi la congestion ou la disponibilité du réseau) en complément des horaires théoriques.</span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a>Ces informations ne sont pas disponible pour l'agglomération de la Rochelle et donc cette possibilité n'est pas explorée.</span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>L'accès aux données GTFS impose quelques limites, comme par exemple la non prise en compte des réseaux scolaires ou d'autres réseaux locaux ou privés non publiés sous ce format.</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a>La modification du réseau de transport comme l'ouverture d'une ligne ou l'accroissement de fréquence est pris en compte en modifiant la matrice des distances et temps par mode entre chaque carreau de résidence et chaque carreau de destination.</span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a>Dans le cas de l'agglomération de la Rochelle, le nombre de paires calculés est de l'ordre de 16 millions.</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a>A partir des temps de trajets par mode, nous appliquons un modèle de choix discret, *Random Utility Model* (RUM) à la McFadden, estimé sur l'enquête mobilité des personnes 2019 @MOBPERS en utilisant les données de mobilités professionnelles @MOBPRO pour caler les flux commune à commune.</span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a>L'estimation de ce modèle est détaillée dans un autre document (référence à insérer).</span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a>Les distances entre chaque paire de cases permettent de calculer un indicateur d'accessibilité qui joue un rôle central dans le modèle radiatif, et donc dans MEAPS, en remplaçant la distance par la somme des opportunités en deçà d'un seuil de temps.</span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>La carte de la @fig-4access représente les temps pour accéder à 10 000 emplois en utilisant différents modes de transport.</span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a><span class="in">```{r carte_access, echo = FALSE}</span></span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-4access</span></span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-scap: "Accessibilité à 10 000 emplois pour la Rochelle"</span></span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Temps d'accès à 10 000 emplois. Pour chaque carreau de résidence, on détermine le temps minimal pour atteindre au moins 10 000 emplois suivant l'un des quatre modes considéré. Cette mesure remplace la distance dans le modèle radiatif. Calcul des auteurs. Sources : OSM, Mapbox, IGN, Conveyal R5, carroyage INSEE 2017, Flores et fichiers fonciers 2018"</span></span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"output/access_4modes.png"</span>)</span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>Les courbes d'accessibilité de la @fig-comaccess sont construite en prenant la moyenne par commune de résidence des temps d'accès pour les différents seuils d'emplois.</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>C'est cette courbe qui découle du modèle théorique présenté plus haut (@sec-meaps) et qui détermine les choix individuels de déplacement comme de localisation.</span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a>Ces courbes font apparaître une propriété propre aux villes littorales : si pour des temps courts ou des moyens de transport peu rapide, l'accès à l'emploi pour des temps courts est maximal à la Rochelle, en revanche, d'autres communes jouissent d'une position plus centrale lorsqu'on accepte des temps de trajets supérieurs à 30 minutes en voiture.</span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a><span class="in">```{r courbe_access, echo= FALSE}</span></span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-comaccess</span></span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-scap: "Accessibilité par communes pour la Rochelle"</span></span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Courbe du temps d'accès aux emplois. Pour chaque commune, on calcule la médianne, pondérée par le nombre d'habitants par carreau, du temps d'accès à différents seuils d'emplois. Cela permet de caractériser les communes par leur accessibilité à l'emploi, une mesure plus pertinente de la 'distance à l'emploi'. Calcul des auteurs. Sources : OSM, Mapbox, IGN, Conveyal R5, carroyage INSEE 2017, Flores et fichiers fonciers 2018"</span></span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"output/access_par_com.png"</span>)</span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a><span class="fu">### Ajustement de MEAPS sur MOBPRO {#sec-ajust}</span></span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a>La construction de la matrice de distance permet d'utiliser MEAPS pour déduire les flux carreau à carreau.</span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a>Mais le fichier détail du recensement et son volet mobilités professionnelles nous donnent une information supplémentaire que nous pouvons utiliser pour calibrer au plus près des données MEAPS.</span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a>Les mobilités professionnelles décrivent pour chaque paire de commune résidence-emploi les flux de mobilités professionnelles (de nombreuses paires de communes ont des flux nuls).</span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a>Cette information est équivalente à celle produite par MEAPS mais agrégée au niveau communal.</span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a>Une première stratégie de calage de MEAPS est d'affecter aux probabilités d'absorption un facteur correcteur pour reproduire le plus fidèlement possible les flux agrégés de @MOBPRO.</span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a>Cette approche permet ensuite d'utiliser MEAPS sur les données @MOBPRO pour réaliser une interpolation infra-communale des déplacements, au carreau 200m.</span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a>En accédant à ce niveau de détail, nous pouvons ensuite mobiliser la méthode de calcul des distances et des temps de trajets à une échelle fine pour produire des différences au carreau 200m.</span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a>Dans une autre approche, plus parcimonieuse, on pourrait limiter le nombre de paramètres estimés pour MEAPS, afin d'une apprécier la qualité prédictive et le comparer à une autre approche.</span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a>Nous détaillerons cette autre approche dans un futur document.</span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a>La modification des probabilités d'absorption est faite par l'ajout d'un facteur correcteur exprimé en "chance", c'est-à-dire que la probabilité modifiée l'est par la formule suivante où $\omicron_{i,j}$ est un nombre entre $0$ et $+\infty$ et $i,j$ indexent les communes de départ et d'arrivée avec $c_a = p_a/(1-p_a)$ :</span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a>\tilde{p}_a = \frac{c_a \times \omicron_{i,j}} {1+c_a \times \omicron_{i,j}} </span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a>$$ {#eq-odd}</span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a>A ce stade nous utilisons un algorithme naïf pour trouver une solution au problème posé.</span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a>Nous calculons l'*odd-ratio* entre le résultat d'une simulation associée à un ensemble d'$\omicron_{i,j}$ et celui défini par les données observées de @MOBPRO en utilisant la formule suivante où $\beta$ est un paramètre d'amortissement inférieur à 1 et positif et $k$ indexe les itérations :</span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a>\omicron^k_{i,j} = (\frac{\tilde{p}^k_a/(1-\tilde{p}^k_a)}{</span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a>p^{mobpro}_a/(1-p^{mobpro}_a)})^\beta \times \omicron^{k-1}_{i,j}</span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a>$$ {#eq-algest}</span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a>Nous modifions alors les $\omicron_{i,j}$ en fonction des écarts observés.</span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>Cela conduit à chercher un point fixe.</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a>Nous calculons ensuite un critère d'ajustement à partir de l'entropie relative de Kullback-Leibler <span class="co">[</span><span class="ot">@kullback1951</span><span class="co">]</span>.</span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a>L'entropie relative est définie pour deux distributions de probabilités $p$ et $q$ comme suit (dans le cas discret, le cas continu se généralise aisément) :</span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a>KL(p,q) = \sum_{i}p_i \times log(p_i/q_i)</span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a>$$ {#eq-kl}</span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a>Cette mesure ressemble à une distance, mais n'est pas symétrique et ne vérifie pas l'inégalité triangulaire.</span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a>Elle s'interprète dans le cadre de la théorie de l'information comme la quantité relative d'information supplémentaire nécessaire pour exprimer $q$ à partir de $p$.</span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a>En suivant @colincameron1997 on peut construire une mesure de la qualité de l'ajustement $R_{KL}^2$ de la façon suivante, où $\hat{q}$ et $q_0$ sont deux distributions respectivement estimée et de référence que l'on compare à $p$ :</span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a>R_{KL}^2 = 1 - \frac{KL(p,\hat{q})}{KL(p, q_0)}</span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a>$$ {#eq-r2kl}</span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a>La distribution de référence est choisie comme une distribution uniforme, par analogie avec le calcul de la variance dans un $R^2$ habituel où l'on régresse sur une constante.</span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a>On écrit :</span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a>\begin{aligned}</span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a>KL(p,q_{ref}) &amp;{}= \sum_{i}p_i \times log(p_i/unif) <span class="sc">\\</span>&amp;{}= \sum_i p_i \times log(p_i) + log(N)</span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a>\end{aligned}</span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a>$$ {#eq-klent}</span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a>qui n'est autre que l'entropie de la distribution $p$ à une constante près ($N$ est le nombre de résidents actifs ou d'emplois).</span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a>L'algorithme employé devra être affiné dans le futur afin de permettre une descente de gradient qui permet de minimiser l'entropie relative.</span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a>L'algorithme naïf permet de réduire cette entropie relative sans assurer qu'elle est minimale.</span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a>Nous utiliserons l'algorithme naïf pour explorer la possibilité d'ajuster MEAPS sur un jeu de données.</span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a>Cet algorithme a été utilisé avec différentes contraintes sur les paramètres.</span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a>Le @tbl-meapsR2 indique la qualité de l'ajustement obtenu dans ces différentes configurations.</span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a>La première est celle où les probabilités d'absorption sont déterminées uniquement par les fuites par commune de résidence.</span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a>C'est la configuration la plus parcimonieuse en termes de paramètres et qui sert de référence.</span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a>Le $R^2_{KL}$ vaut 89.1% ce qui est déjà un ajustement élevé.</span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a>La seconde configuration est celle où l'on ajuste des $\omicron_{i,j}$ uniquement pour les termes diagonaux ($i=j$).</span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a>Cette configuration ajuste donc un *odd-ratio* pour les résidents qui travaillent dans leur commune de résidence.</span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a>Dans un certain nombre de communes, cet ajustement conduit à augmenter la probabilité d'absorption interne (@fig-carteodd), ce qui indique que le choix de résidence n'est pas indépendant de celui d'activité.</span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a>Pour la commune la plus importante (la Rochelle), en revanche, l'*odd-ratio* $\omicron_{17300, 17300}$ est proche de 1.</span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a>Les deux configurations suivantes laissent beaucoup plus de degrés de liberté en estimant des $\omicron_{i,j}$ librement.</span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a>La première de ces deux configurations limite les $\omicron_{i,j}$ estimés à ceux représentant un total cumulé des flux mesurés par @MOBPRO égal à 98% ce qui représente un peu moins de 2 000 $\omicron_{i,j}$.</span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a>La seconde configuration estime tous les $\omicron_{i,j}$ sans limite (soit 15 120 paramètres pour 72 communes de résidence et 210 communes d'activité).</span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a><span class="in">```{r meapsR2, echo=FALSE}</span></span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-meapsR2</span></span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: Ajustement de MEAPS</span></span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"output/alg3.srda"</span>)</span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a>tr2 <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">config =</span> <span class="st">"Fuite par commune de résidence"</span>,</span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a>               <span class="at">n_fuite =</span> <span class="dv">72</span>,</span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a>               <span class="at">n_params =</span> <span class="dv">0</span>,</span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a>               <span class="at">r2kl =</span> stats <span class="sc">|&gt;</span> </span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">filter</span>(model<span class="sc">==</span><span class="dv">1</span>) <span class="sc">|&gt;</span> </span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">pull</span>(r2kl))</span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a>tr2 <span class="ot">&lt;-</span>tr2 <span class="sc">|&gt;</span> </span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>(<span class="fu">tibble</span>(<span class="at">config =</span> <span class="st">"Fuite et diagonale"</span>,</span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a>                   <span class="at">n_fuite =</span> <span class="dv">72</span>, </span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a>                   <span class="at">n_params =</span> <span class="dv">72</span>,</span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a>                   <span class="at">r2kl =</span> stats <span class="sc">|&gt;</span> </span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">filter</span>(model<span class="sc">&gt;</span><span class="dv">10</span>) <span class="sc">|&gt;</span></span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">filter</span>(r2kl<span class="sc">==</span><span class="fu">max</span>(r2kl)) <span class="sc">|&gt;</span> </span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">pull</span>(r2kl) <span class="sc">|&gt;</span> </span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">pluck</span>(<span class="dv">1</span>)))</span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"output/alg2p.srda"</span>)</span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a>tr2 <span class="ot">&lt;-</span> tr2 <span class="sc">|&gt;</span> </span>
<span id="cb1-210"><a href="#cb1-210" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>(<span class="fu">tibble</span>(<span class="at">config =</span> <span class="st">"Fuite et 90% des flux"</span>,</span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a>                   <span class="at">n_fuite =</span> <span class="dv">72</span>,</span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a>                   <span class="at">n_params =</span> <span class="dv">729</span>,</span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a>                   <span class="at">r2kl =</span> stats <span class="sc">|&gt;</span> </span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">filter</span>(model<span class="sc">&gt;</span><span class="dv">10</span>) <span class="sc">|&gt;</span></span>
<span id="cb1-215"><a href="#cb1-215" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">filter</span>(r2kl<span class="sc">==</span><span class="fu">max</span>(r2kl)) <span class="sc">|&gt;</span></span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">pull</span>(r2kl) <span class="sc">|&gt;</span> </span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">pluck</span>(<span class="dv">1</span>)))</span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"output/alg2.srda"</span>)</span>
<span id="cb1-219"><a href="#cb1-219" aria-hidden="true" tabindex="-1"></a>tr2 <span class="ot">&lt;-</span> tr2 <span class="sc">|&gt;</span> </span>
<span id="cb1-220"><a href="#cb1-220" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>(<span class="fu">tibble</span>(<span class="at">config =</span> <span class="st">"Fuite et 99% des flux"</span>,</span>
<span id="cb1-221"><a href="#cb1-221" aria-hidden="true" tabindex="-1"></a>                   <span class="at">n_fuite =</span> <span class="dv">72</span>,</span>
<span id="cb1-222"><a href="#cb1-222" aria-hidden="true" tabindex="-1"></a>                   <span class="at">n_params =</span> <span class="dv">1928</span>,</span>
<span id="cb1-223"><a href="#cb1-223" aria-hidden="true" tabindex="-1"></a>                   <span class="at">r2kl =</span> stats <span class="sc">|&gt;</span> </span>
<span id="cb1-224"><a href="#cb1-224" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">filter</span>(model<span class="sc">&gt;</span><span class="dv">10</span>) <span class="sc">|&gt;</span></span>
<span id="cb1-225"><a href="#cb1-225" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">filter</span>(r2kl<span class="sc">==</span><span class="fu">max</span>(r2kl)) <span class="sc">|&gt;</span></span>
<span id="cb1-226"><a href="#cb1-226" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">pull</span>(r2kl) <span class="sc">|&gt;</span> </span>
<span id="cb1-227"><a href="#cb1-227" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">pluck</span>(<span class="dv">1</span>)))</span>
<span id="cb1-228"><a href="#cb1-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-229"><a href="#cb1-229" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"output/alg4.srda"</span>)</span>
<span id="cb1-230"><a href="#cb1-230" aria-hidden="true" tabindex="-1"></a>tr2 <span class="ot">&lt;-</span> tr2 <span class="sc">|&gt;</span> </span>
<span id="cb1-231"><a href="#cb1-231" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>(<span class="fu">tibble</span>(<span class="at">config =</span> <span class="st">"Fuite et 100% des flux"</span>,</span>
<span id="cb1-232"><a href="#cb1-232" aria-hidden="true" tabindex="-1"></a>                   <span class="at">n_fuite =</span> <span class="dv">72</span>,</span>
<span id="cb1-233"><a href="#cb1-233" aria-hidden="true" tabindex="-1"></a>                   <span class="at">n_params =</span> <span class="dv">15120</span>,</span>
<span id="cb1-234"><a href="#cb1-234" aria-hidden="true" tabindex="-1"></a>                   <span class="at">r2kl =</span> stats <span class="sc">|&gt;</span> </span>
<span id="cb1-235"><a href="#cb1-235" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">filter</span>(model<span class="sc">&gt;</span><span class="dv">10</span>) <span class="sc">|&gt;</span></span>
<span id="cb1-236"><a href="#cb1-236" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">filter</span>(r2kl<span class="sc">==</span><span class="fu">max</span>(r2kl)) <span class="sc">|&gt;</span></span>
<span id="cb1-237"><a href="#cb1-237" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">pull</span>(r2kl)))</span>
<span id="cb1-238"><a href="#cb1-238" aria-hidden="true" tabindex="-1"></a>tr2 <span class="sc">|&gt;</span> </span>
<span id="cb1-239"><a href="#cb1-239" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gt</span>() <span class="sc">|&gt;</span> </span>
<span id="cb1-240"><a href="#cb1-240" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cols_label</span>(<span class="at">config =</span> <span class="st">""</span>,</span>
<span id="cb1-241"><a href="#cb1-241" aria-hidden="true" tabindex="-1"></a>             <span class="at">n_fuite =</span> <span class="fu">md</span>(<span class="st">"N(p&lt;sub&gt;f,i&lt;/sub&gt;)"</span>),</span>
<span id="cb1-242"><a href="#cb1-242" aria-hidden="true" tabindex="-1"></a>             <span class="at">n_params =</span> <span class="fu">md</span>(<span class="st">"N(o&lt;sub&gt;i,j&lt;/sub&gt;)"</span>),</span>
<span id="cb1-243"><a href="#cb1-243" aria-hidden="true" tabindex="-1"></a>             <span class="at">r2kl =</span> <span class="fu">md</span>(<span class="st">"R&lt;sub&gt;KL&lt;/sub&gt;&lt;sup&gt;2&lt;/sup&gt;"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb1-244"><a href="#cb1-244" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fmt_percent</span>(<span class="at">columns =</span> r2kl, <span class="at">decimals=</span><span class="dv">1</span>) <span class="sc">|&gt;</span> </span>
<span id="cb1-245"><a href="#cb1-245" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fmt_integer</span>(<span class="at">columns =</span> <span class="fu">c</span>(n_fuite, n_params), <span class="at">sep_mark=</span><span class="st">" "</span>) <span class="sc">|&gt;</span> </span>
<span id="cb1-246"><a href="#cb1-246" aria-hidden="true" tabindex="-1"></a>  gt<span class="sc">::</span><span class="fu">tab_footnote</span>(<span class="fu">md</span>(<span class="st">"L'ajustement de MEAPS est réalisé par l'algorithme décrit dans le texte. Le nombre de paramètres estimés est égal à la somme de la colonne N(p&lt;sub&gt;f,i&lt;/sub&gt;) et de la colonne N(o&lt;sub&gt;i,j&lt;/sub&gt;)."</span>))</span>
<span id="cb1-247"><a href="#cb1-247" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-248"><a href="#cb1-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-249"><a href="#cb1-249" aria-hidden="true" tabindex="-1"></a>la @fig-actvsfit représente les flux observés et estimés pour les différentes configurations du @tbl-meapsR2.</span>
<span id="cb1-250"><a href="#cb1-250" aria-hidden="true" tabindex="-1"></a>Le gain à estimer les $\omicron_{i,i}$ diagonaux, pondérant les flux allant d'une commune de résidence vers elle même est assez élevé, faisant passer le $R^2_{KL}$ de 89.1% à 94.3% et réduisant les écarts entre flux observé et flux estimé comme le montrent les deux panneaux supérieurs de la @fig-actvsfit.</span>
<span id="cb1-251"><a href="#cb1-251" aria-hidden="true" tabindex="-1"></a>L'ajout de paramètres supplémentaires ne fait pas gagner beaucoup plus d'autant que les écarts pour les flux marginaux ne sont pas tant réduit que ça.</span>
<span id="cb1-252"><a href="#cb1-252" aria-hidden="true" tabindex="-1"></a>La limite de l'algorithme naïf apparaît ici, puisque le modèle complètement saturé n'ajuste pas totalement la distribution.</span>
<span id="cb1-253"><a href="#cb1-253" aria-hidden="true" tabindex="-1"></a>Différents détails de l'algorithme peuvent l'expliquer, notamment la censure des *odd-ratio* trop faibles (<span class="sc">\&lt;</span>0.0001) ou trop importants (<span class="sc">\&gt;</span>10000) ou la prise en compte des flux nuls.</span>
<span id="cb1-254"><a href="#cb1-254" aria-hidden="true" tabindex="-1"></a>Au-delà de cet argument, il est probable que pour converger vers un ajustement plus strict, il serait nécessaire de calculer la matrice des quasi dérivées des flux par rapport aux $\omicron_{i,j}$.</span>
<span id="cb1-255"><a href="#cb1-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-256"><a href="#cb1-256" aria-hidden="true" tabindex="-1"></a>Mais le coût peut être très élevé puisque cette matrice (calculée dans la partie synthétique dans un cas simple) est d'une taille considérable (15 120 $\times$ 15 120 coefficients), surtout si l'on prend en compte que le calcul de chaque terme prend quelques dizaine de secondes<span class="ot">[^11]</span>.</span>
<span id="cb1-257"><a href="#cb1-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-258"><a href="#cb1-258" aria-hidden="true" tabindex="-1"></a><span class="ot">[^11]: </span>Autour de mille années de vCPU...</span>
<span id="cb1-259"><a href="#cb1-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-260"><a href="#cb1-260" aria-hidden="true" tabindex="-1"></a><span class="in">```{r actvsfit}</span></span>
<span id="cb1-261"><a href="#cb1-261" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-actvsfit</span></span>
<span id="cb1-262"><a href="#cb1-262" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-scap: MEAPS observés versus estimés</span></span>
<span id="cb1-263"><a href="#cb1-263" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "La figure présente pour chaque configuration d'estimation le flux observé (axe des x) et le flux estimé (axe des y) en bleu lorsque o&lt;sub&gt;i,j&lt;/sub&gt; est estimé et en rouge lorsque o&lt;sub&gt;i,j&lt;/sub&gt; n'est pas estimé (les fuites sont toujours utilisées). La valeur de référence est répétée dans chaque panneau en gris clair."</span></span>
<span id="cb1-264"><a href="#cb1-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-265"><a href="#cb1-265" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"output/estmeaps.png"</span>)</span>
<span id="cb1-266"><a href="#cb1-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-267"><a href="#cb1-267" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-268"><a href="#cb1-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-269"><a href="#cb1-269" aria-hidden="true" tabindex="-1"></a>Pour les 20 plus grandes communes de l'agglomération de la Rochelle -- qui comptent plus de 1 000 résidents en activité -- on peut représenter les *odd-ratios,* construits comme le ratio des chances ($p_{a,i,j}/(1-p_{a,i,j}$)) estimées dans la configuration 100% des flux par rapport aux chances calculées dans le cas où tous les $\omicron_{i,j}$ sont égaux à 1, en fonction de la distance de la commune de destination à la commune de résidence<span class="ot">[^12]</span>.</span>
<span id="cb1-270"><a href="#cb1-270" aria-hidden="true" tabindex="-1"></a>Ce diagramme, analogue à un spectre, peut aussi être constuit par commune de destination, la distance $d$ étant la distance aux différentes communes de résidence @fig-spectreE. L'élément le plus frappant est que les *odd-ratios* de $i$ à $i$ sont généralement supérieur à 1 (@fig-spectreR), à l'exception de la commune de la Rochelle.</span>
<span id="cb1-271"><a href="#cb1-271" aria-hidden="true" tabindex="-1"></a>Il n'émerge pas de structure particulière par rapport à la distance, si ce n'est des *odd-ratios* élevés pour des distances importantes</span>
<span id="cb1-272"><a href="#cb1-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-273"><a href="#cb1-273" aria-hidden="true" tabindex="-1"></a><span class="ot">[^12]: </span>La distance est construite comme la distance moyenne pondérée entre les résidents de la commune de départ et les emplois de la commune d'arrivée.</span>
<span id="cb1-274"><a href="#cb1-274" aria-hidden="true" tabindex="-1"></a>    La pondération est le produit des emplois et des résidents pour chaque paire, normalisé à 1.</span>
<span id="cb1-275"><a href="#cb1-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-276"><a href="#cb1-276" aria-hidden="true" tabindex="-1"></a><span class="in">```{r spectreR, results="asis"}</span></span>
<span id="cb1-277"><a href="#cb1-277" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-spectreR</span></span>
<span id="cb1-278"><a href="#cb1-278" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-scap: "Odd-ratio par commune de résidence fonction de la distance aux communes d'emploi (spectre résidents)"</span></span>
<span id="cb1-279"><a href="#cb1-279" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "La figure représente pour les 20 plus grandes communes de l'agglomération de la Rochelle les odd-ratios estimés (configuration 100% des flux) en fonction de la distance entre cette commune et les communes où travaillent les résidents. Les points marqués d'un petit point blancs sont les emplois situés hors du périmètre du SCoT."</span></span>
<span id="cb1-280"><a href="#cb1-280" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"output/spectre effectif par COMMUNE 100.png"</span>)</span>
<span id="cb1-281"><a href="#cb1-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-282"><a href="#cb1-282" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-283"><a href="#cb1-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-284"><a href="#cb1-284" aria-hidden="true" tabindex="-1"></a><span class="in">```{r spectreE}</span></span>
<span id="cb1-285"><a href="#cb1-285" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-spectreE</span></span>
<span id="cb1-286"><a href="#cb1-286" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-scap: "Odd-ratio par commune d'emploi fonction de la distance aux communes de résidence (spectre emplois)"</span></span>
<span id="cb1-287"><a href="#cb1-287" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "La figure représente pour les 13 plus grandes communes d'emplois du pérmiètre géographique (33 km autour de l'agglomération de la Rochelle) les odd-ratios estimés (configuration 100% des flux) en fonction de la distance entre cette commune et les communes où résident les travailleurs de la commune."</span></span>
<span id="cb1-288"><a href="#cb1-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-289"><a href="#cb1-289" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"output/spectre effectif par DCLT 100.png"</span>)</span>
<span id="cb1-290"><a href="#cb1-290" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-291"><a href="#cb1-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-292"><a href="#cb1-292" aria-hidden="true" tabindex="-1"></a>La @fig-carteodd permet de préciser la valeur élevée des *odd-ratios* pour les flux internes.</span>
<span id="cb1-293"><a href="#cb1-293" aria-hidden="true" tabindex="-1"></a>Les communes où sont localisés de nombreux emplois ont un *odd-ratio* plutôt plus faible alors qu'ils sont estimés plus élevés dans les communes plus petites et moins desservies.</span>
<span id="cb1-294"><a href="#cb1-294" aria-hidden="true" tabindex="-1"></a>Pour les différentes procédure d'estimation et donc différents nombres de paramètres estimés, on observe une structure similaire dans la répartition géographique des *odd-ratio*, ce qui suggère que les *odd-ratios* estimés contiennent de l'information.</span>
<span id="cb1-295"><a href="#cb1-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-296"><a href="#cb1-296" aria-hidden="true" tabindex="-1"></a>Un *odd-ratio* élevé indique que les flux internes sont plus élevés que dans le scénario de référence.</span>
<span id="cb1-297"><a href="#cb1-297" aria-hidden="true" tabindex="-1"></a>Cela indique probablement un choix de résidence en lien avec l'emploi occupé en privilégiant la commune d'activité pour la résidence (ou l'inverse).</span>
<span id="cb1-298"><a href="#cb1-298" aria-hidden="true" tabindex="-1"></a>Le spectre résident en fonction de la distance indique que ce phénomène, s'il est une hypothèse à très faible distance, ne persiste pas en dehors de la commune de résidence.</span>
<span id="cb1-299"><a href="#cb1-299" aria-hidden="true" tabindex="-1"></a>En revanche, la @fig-spectreE suggère que dans certaines communes, notamment Surgères, on observe des *odd-ratios* supérieurs à 1 pour les des distances faibles, ce qui tend à indiquer que les habitants des communes alentours privilégient Surgères comme lieu d'emploi.</span>
<span id="cb1-300"><a href="#cb1-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-301"><a href="#cb1-301" aria-hidden="true" tabindex="-1"></a>A ce stade, les observations sont limitées par le faible nombre de communes modélisées, mais on peut espérer que l'analyse des *odd-ratios* estimés pourra servir à caractériser les communes en fonction des choix de résidence et d'emploi.</span>
<span id="cb1-302"><a href="#cb1-302" aria-hidden="true" tabindex="-1"></a>En multipliant cette analyse pour d'autres territoires, l'information apportée par les *odd-ratio* pourra être inférée.</span>
<span id="cb1-303"><a href="#cb1-303" aria-hidden="true" tabindex="-1"></a>Il sera aussi possible de confronter ces éléments à d'autres variables, comme le prix de l'immobilier, les loyers résidentiels ou commerciaux, la densité d'emploi.</span>
<span id="cb1-304"><a href="#cb1-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-305"><a href="#cb1-305" aria-hidden="true" tabindex="-1"></a>Une autre approche empirique serait de définir une forme fonctionnelle pour les *odd-ratio* en paramétrant cette forme fonctionnelle de façon parcimonieuse.</span>
<span id="cb1-306"><a href="#cb1-306" aria-hidden="true" tabindex="-1"></a>On pourra alors tester des hypothèses et tenter d'extraire une information de la structure des *odd-ratios.* Une autre approche est de procéder à une analyse de régression multivariée sur les *odd-ratios* estimés.\</span>
<span id="cb1-307"><a href="#cb1-307" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-308"><a href="#cb1-308" aria-hidden="true" tabindex="-1"></a><span class="in">```{r carteodd}</span></span>
<span id="cb1-309"><a href="#cb1-309" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-carteodd</span></span>
<span id="cb1-310"><a href="#cb1-310" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-scap: "Odd-ratio dans la diagonale"</span></span>
<span id="cb1-311"><a href="#cb1-311" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Chaque cercle indique les odd-ratio estimés dans la diagonale (100% des flux). Les diamètres des cercles sont proportionels aux flux internes (de i à i)."</span></span>
<span id="cb1-312"><a href="#cb1-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-313"><a href="#cb1-313" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"output/toutes configs odds effectifs.png"</span>)</span>
<span id="cb1-314"><a href="#cb1-314" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-315"><a href="#cb1-315" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-316"><a href="#cb1-316" aria-hidden="true" tabindex="-1"></a><span class="fu">### Scénarios "localisation de l'emploi"</span></span>
<span id="cb1-317"><a href="#cb1-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-318"><a href="#cb1-318" aria-hidden="true" tabindex="-1"></a>Le Schéma de Cohérence Territorial (SCoT) est un document de planification, établi et voté par les élus des communes composant le territoire et soumis à validation de l'État.</span>
<span id="cb1-319"><a href="#cb1-319" aria-hidden="true" tabindex="-1"></a>Il défini, entre autres, des zones de développement économique, urbaines et des espaces naturels.</span>
<span id="cb1-320"><a href="#cb1-320" aria-hidden="true" tabindex="-1"></a>C'est la loi SRU relative à la Solidarité et au Renouvellement Urbains du 13 décembre 2000 qui l'a défini et les contours en ont été modifiés au cours des dernières années.</span>
<span id="cb1-321"><a href="#cb1-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-322"><a href="#cb1-322" aria-hidden="true" tabindex="-1"></a>Le schéma n'est pas qu'indicatif puisqu'il est opposable.</span>
<span id="cb1-323"><a href="#cb1-323" aria-hidden="true" tabindex="-1"></a>En ce qui concerne le développement de l'emploi, la création de zones d'activité est rendue possible par le SCoT, mais la réalisation effective des créations d'emploi et surtout leur localisation nette des déplacements d'autres emplois découle des décisions de l'ensemble des acteurs et donc et donc de causalités diverses et variées.</span>
<span id="cb1-324"><a href="#cb1-324" aria-hidden="true" tabindex="-1"></a>Nous évaluons ici des scénarios comptatible avec le SCoT sans pour autant nous prononcer quant à leur réalisme ou leur probabilité d'occurrence.</span>
<span id="cb1-325"><a href="#cb1-325" aria-hidden="true" tabindex="-1"></a>Ainsi, nous analysons les localisations proposées à emploi total constant, c'est-à-dire vues comme des relocalisations de l'emploi vers les zones d'activités depuis leur localisation actuelle.</span>
<span id="cb1-326"><a href="#cb1-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-327"><a href="#cb1-327" aria-hidden="true" tabindex="-1"></a>La construction de cette analyse impose donc de connaître précisément la localisation de l'emploi, ce que nous réalisons par une imputation au carreau INSPIRE 200m à partir des données d'emploi par commune.</span>
<span id="cb1-328"><a href="#cb1-328" aria-hidden="true" tabindex="-1"></a>Nous calons alors MEAPS sur ces données ainsi que sur les données de mobilité professionnelles issues du recensement<span class="ot">[^13]</span> et publiées par l'INSEE.</span>
<span id="cb1-329"><a href="#cb1-329" aria-hidden="true" tabindex="-1"></a>Ces données donnent les lieux habituels de travail (à la commune) pour les différents résidents (d'une commune) ainsi que les flux correspondant entre paires de communes.</span>
<span id="cb1-330"><a href="#cb1-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-331"><a href="#cb1-331" aria-hidden="true" tabindex="-1"></a><span class="ot">[^13]: https://www.insee.fr/fr/information/2383243</span></span>
<span id="cb1-332"><a href="#cb1-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-333"><a href="#cb1-333" aria-hidden="true" tabindex="-1"></a>La construction de cette analyse impose donc de connaître précisément la localisation de l'emploi, ce que nous réalisons par une imputation au carreau INSPIRE 200m à partir des données d'emploi par commune.</span>
<span id="cb1-334"><a href="#cb1-334" aria-hidden="true" tabindex="-1"></a>Nous calons alors MEAPS sur ces données ainsi que sur les données de mobilité professionnelles issues du recensement<span class="ot">[^14]</span> et publiées par l'INSEE.</span>
<span id="cb1-335"><a href="#cb1-335" aria-hidden="true" tabindex="-1"></a>Ces données donnent les lieux habituels de travail (à la commune) pour les différents résidents (d'une commune) ainsi que les flux correspondant entre paires de communes.</span>
<span id="cb1-336"><a href="#cb1-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-337"><a href="#cb1-337" aria-hidden="true" tabindex="-1"></a><span class="ot">[^14]: </span>Autour de mille années de vCPU...</span>
<span id="cb1-338"><a href="#cb1-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-339"><a href="#cb1-339" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Une fois MEAPS calé sur ces données, nous pouvons analyser des scénarios de déplacement des emplois et en déduire les conséquences en trajets, mode de transport et donc émissions de CO~2~ associé</span>
<span id="cb1-340"><a href="#cb1-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-341"><a href="#cb1-341" aria-hidden="true" tabindex="-1"></a><span class="fu">### Scénarios "transport en commun"</span></span>
<span id="cb1-342"><a href="#cb1-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-343"><a href="#cb1-343" aria-hidden="true" tabindex="-1"></a>L'analyse du territoire ne repose pas seulement sur la localisation de l'emploi, mais aussi sur une prise en compte détaillée des possibilités de transport.</span>
</code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>